---
title: "Cadu"
output: 
  word_document:
    toc: yes
  html_document:
    highlight: tango
    lib_dir: libs
    number_sections: yes
    theme: yeti
    toc: yes
    toc_float:
      collapse: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r}
library(dplyr)
library(readxl)
library(data.table)
library(abjutils)
library(stringr)
library(foreign)
library(tidyr)
```


```{r}
library(readr)
load("/cloud/project/bases usadas/var_IBGE_ba.RData")
cadu_2016 <- read.csv("misocial_2016.csv", sep = ",")%>% dplyr::filter(ibge %in% var_IBGE_ba) 

cadu_ba_2016_12<-cadu_2016%>%filter(anomes==201612)%>%mutate(ano=2016)
  
  
```


```{r}
cadu_2017 <- read.csv("misocial_2017.csv", sep = ",")%>% dplyr::filter(ibge %in% var_IBGE_ba) 

cadu_ba_2017_12<-cadu_2017%>%filter(anomes==201712)%>%mutate(ano=2017)
  

```


```{r}
cadu_2018 <- read.csv("misocial_2018.csv", sep = ",")%>% dplyr::filter(ibge %in% var_IBGE_ba) 
# correcao em 25.11.2022, seleciono apenas mes 12

cadu_ba_2018_12<-cadu_2018%>%filter(anomes==201812)%>%mutate(ano=2018)

```

```{r}
cadu_2019 <- read.csv("misocial_2019.csv", sep = ",")%>% dplyr::filter(ibge %in% var_IBGE_ba) 

# correcao em 25.11.2022, seleciono apenas mes 12

cadu_ba_2019_12<-cadu_2019%>%filter(anomes==201912)%>%mutate(ano=2019)

```


```{r}
load("/cloud/project/binomial/bases finais/municipio_ba_geral.RData")
```


```{r}
cadu_ba_16_19_12 <-rbind(cadu_ba_2016_12,cadu_ba_2017_12,cadu_ba_2018_12,cadu_ba_2019_12)
cadu_ba_16_19_12<-cadu_ba_16_19_12%>%dplyr::select(-2)%>%
  left_join(municipio_ba_geral %>% dplyr::select(mun,IBGE_6), by = c('ibge'='IBGE_6'))%>%
  dplyr::select(ibge,mun,ano,everything())

```


```{r}
load("/cloud/project/binomial/bases finais/base_analise_ha.RData")
load("/cloud/project/binomial/bases finais/base_analise_ha_1.RData")
```


```{r}
cadu_ba_16_19_12 = cadu_ba_16_19_12 %>% left_join(base_analise_ha %>% dplyr::select(mun,ano,populacao),by = c('mun' = 'mun','ano'='ano'))%>%
mutate('tx_cadunico_tot_pes_1' = round(100000 * (cadu_ba_16_19_12$cadunico_tot_pes/populacao), 3))%>%
  mutate('tx_cadunico_tot_pes_pob_ext_1' = round(100000 * (cadu_ba_16_19_12$cadunico_tot_pes_pob_e_ext_pob/populacao), 3))%>%
  mutate('tx_cadunico_tot_pes_pob_1' = round(100000 * (cadu_ba_16_19_12$cadunico_tot_pes_pob/populacao), 3))%>%
  mutate('tx_cadunico_tot_pes' = round((cadu_ba_16_19_12$cadunico_tot_pes/populacao), 3))%>%
  mutate('tx_cadunico_tot_pes_pob_ext' = round((cadu_ba_16_19_12$cadunico_tot_pes_pob_e_ext_pob/populacao), 3))%>%
  mutate('tx_cadunico_tot_pes_pob' = round((cadu_ba_16_19_12$cadunico_tot_pes_pob/populacao), 3))%>%
  dplyr::select(ibge,mun,ano, populacao,everything())

save(cadu_ba_16_19_12, file="/cloud/project/binomial/bases finais/cadu_ba_16_19_12.RData")
```

# atualizar bases base analises

```{r}
base_analise_ha_v2 = base_analise_ha %>% dplyr::select(-19)%>%
  left_join(cadu_ba_16_19_12 %>% dplyr::select(mun,ano,tx_cadunico_tot_pes, tx_cadunico_tot_pes_pob),by = c('mun' = 'mun','ano'='ano'))


save(base_analise_ha_v2, file="/cloud/project/binomial/bases finais/base_analise_ha_v2.RData")
```

```{r}
base_analise_ha_1_v2 = base_analise_ha_1 %>% dplyr::select(-19)%>%
  left_join(cadu_ba_16_19_12 %>% dplyr::select(mun,ano,tx_cadunico_tot_pes_1, tx_cadunico_tot_pes_pob_1),by = c('mun' = 'mun','ano'='ano'))


save(base_analise_ha_1_v2, file="/cloud/project/binomial/bases finais/base_analise_ha_1_v2.RData")
```