---
title: "Análise Descritiva Arboviroses 2016-2019"
output:
  word_document:
    toc: yes
  html_document:
    highlight: tango
    lib_dir: libs
    number_sections: yes
    theme: yeti
    toc: yes
    toc_float:
      collapse: yes
---

```{r setup,include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, comment = '', warning = FALSE)
```

```{r}
library(data.table)
library(tidyverse)
library(dplyr)
library(read.dbc)
library(foreign)
library(dplyr)
require("stringr")
require(summarytools)
library(rapportools)
source("http://pcwww.liv.ac.uk/~william/R/crosstab.r")
```

<!-- # Leitura da base -->
```{r}
library(tibble)
library(readxl)
```

```{r}
#setwd("C:/Users/Visitante/Downloads/SINAN/dados_dengue/raw/")
```

```{r}
#nome.arquivo<-"Arboviroses casos confirmados notificados Bahia 2016 - 2019"
#load("G:/backup_maira/SINAN/analisebruno/arboviroses.Rdata")
#load("/cloud/project/fe_dataset_arboviroses_fase1.RData")
load("/cloud/project/fe_base de casos corrigidas/fe_dataset_arboviroses_fase1.RData")
load("/cloud/project/binomial/bases finais/base_analise_ha_v2.RData")
load("/cloud/project/binomial/bases finais/bahia_pop_long.RData")
load("/cloud/project/binomial/scrpits/autoctone/data_arbo_autoc_att_vcasos_e_tx.RData")
```

```{r}
#dng<-fe_dengue_conf
#zk<-fe_zika_conf
#chik<-fe_chik_conf
```

# Estrutura da base

## zika
```{r}
names(fe_zika_conf)
```
# Casos confirmados por ano


```{r}
base_analise_ha_v2%>%dplyr::select(ano,zika_conf)%>%
 dplyr::filter(zika_conf>0)%>%
 group_by(ano)%>%  
 dplyr::summarise_at(c("zika_conf"), sum, na.rm = TRUE)%>%
 sort_asc(ano,zika_conf)%>%
 knitr::kable(.,"simple")

```
# casos suspeitos por ano
 
```{r}
fe_zika_susp_muni%>%
 dplyr::filter(casos_zika>0)%>%
 group_by(NU_ANO)%>%  
 dplyr::summarise_at(c("casos_zika"), sum, na.rm = TRUE)%>%
 sort_asc(NU_ANO,casos_zika)

```
# Desfecho
1-Cura
2- Óbito por zk
3- Óbito por outras causas
4 – Óbito em investigação
9- Ignorado

```{r}
fe_zika_conf%>%
    dplyr::select(MUN_RESI,NU_ANO,TPAUTOCTO,DT_NOTIFIC,EVOLUCAO)%>%
    mutate(DT_NOTIFIC = as.Date(DT_NOTIFIC)) %>% 
    mutate(mes_ano = format(DT_NOTIFIC, "%m/%Y")) %>% 
    mutate(mes=format(DT_NOTIFIC, "%m"))%>%
    group_by(mes_ano, MUN_RESI)%>%count()%>%
    dplyr::rename(casos_chik=freq)%>%
    dplyr::select(TPAUTOCTO,EVOLUCAO,mes)%>%
    dfSummary(style='multiline', graph.col = FALSE)
```

# zika municipios ao longo dos 4 anos
 
```{r}
zk<-base_analise_ha_v2%>%dplyr::select(ano,mun,zika_conf)%>%
 dplyr::filter(zika_conf>0)%>%
 group_by(ano)

mun2016<-zk$mun[zk$ano==2016]
mun2017<-zk$mun[zk$ano==2017]
mun2018<-zk$mun[zk$ano==2018]
mun2019<-zk$mun[zk$ano==2019]
```

```{r}
uni_16_17<-intersect(mun2016,mun2017)
uni_161718<-intersect(uni_16_17,mun2018)
uni_16171819<-intersect(uni_161718,mun2019)
uni_16171819
```

```{r}
bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::select(macrorregiao,regiao.de.saude,mun)%>%
#  dplyr::group_by(macrorregiao,regiao.de.saude)%>%
  sort_desc(macrorregiao,regiao.de.saude)%>%
  knitr::kable(.,"simple")
```
## caracteristicas municipios
```{r}
bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::filter(ano==2016)%>%
  dplyr::select(mun,popporte,IDH,bioma_2014,newtipology,tipologia)%>%
  knitr::kable(.,"pipe",align = "c")

```

```{r}
bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::select(mun,ano)%>%
  left_join(indicadores_ba%>%dplyr::select(1:2,11,21,26),by = c('mun' = 'mun', 'ano'='ano'))%>%
  knitr::kable(.,"pipe",align = "c")
```

```{r}
base<-bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::select(mun,ano)%>%
  left_join(indicadores_ba%>%dplyr::select(1:2,11,21,26),by = c('mun' = 'mun', 'ano'='ano'))

base%>% 
    gather('variavel','taxa',tx_cadunico_tot_pes_pob_ext)%>%
  mutate(variavel = fct_reorder(variavel, taxa,.desc = TRUE)) %>%
ggplot(aes(x=taxa, y=mun, fill=variavel)) +
    geom_boxplot(alpha=0.2)+
    theme_ipsum() +
    xlab(" Pobres inscritos no Cadastro Único")+
    ylab("Municipio")+
    theme(axis.text.y=element_text(size=5),axis.text.x = element_text(size=5)
        )#+facet_wrap(~variavel)


```


```{r}
percent_snis<-indicadores_ba%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::filter(ano==2016)%>%
  dplyr::select(mun, pop_2015,cadu_Ssnis_2015,cadu_Ssnis)%>%
  group_by(mun)%>%
 # mutate(cadu_Ssnis=sum(cadu_Ssnis))%>%
  dplyr::summarise_at(c("cadu_Ssnis","pop_2015"), sum, na.rm = TRUE)%>%
  mutate(percent_Ssnis= round(((cadu_Ssnis/(pop_2015-1))*100),3))%>%# percentual
  sort_asc(percent_Ssnis,mun)

percent_snis%>%
 # dfSummary(style='multiline', graph.col = FALSE)
  knitr::kable(.,"simple")
```

```{r}
base_analise_ha_v2%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::select(mun,ano,tx_vacina,tx_G12A,tx_fluxo,tx_cadunico_tot_pes_pob_ext)%>%
  gather('variavel','taxa',tx_vacina,tx_G12A,tx_fluxo,tx_cadunico_tot_pes_pob_ext)%>%
  mutate(variavel = fct_reorder(variavel, taxa,.desc = TRUE)) %>%
ggplot(aes(x=taxa, y=mun, fill=variavel)) +
    geom_boxplot(alpha=0.2)+
    theme_ipsum() +
    xlab(" Taxas do município")+
    ylab("Municipio")+
    theme(axis.text.y=element_text(size=5),axis.text.x = element_text(size=5)
        ) +facet_wrap(~variavel,nrow=2)
#+ theme(legend.position='none')
```


```{r}
bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::filter(ano==2016)%>%
  dplyr::select(regiao.de.saude,macrorregiao,popporte,IDH_2015,IDH,bioma_2014,tipologia)%>%
  dfSummary(style='multiline', graph.col = FALSE)
```

```{r}

zika<-cadu_ba_16_19_12%>%
  dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::select(mun,ano,ibge,populacao)%>%
  left_join(fe_zika_conf%>%dplyr::select(ID_MN_RESI,NU_ANO,TPAUTOCTO,DT_NOTIFIC,EVOLUCAO),by = c('ibge' = 'ID_MN_RESI','ano'='NU_ANO'))

zika%>%
   mutate(DT_NOTIFIC = as.Date(DT_NOTIFIC)) %>% 
    mutate(mes_ano = format(DT_NOTIFIC, "%m/%Y")) %>% 
    mutate(mes=format(DT_NOTIFIC, "%m"))%>%
    group_by(mes_ano, mun)%>%count()%>%
    dplyr::rename(casos_chik=freq)%>%
    dplyr::select(TPAUTOCTO,EVOLUCAO,mes)%>%
    dfSummary(style='multiline', graph.col = FALSE)
```
### Autóctones

```{r}
zika%>%
    dplyr::select(mun,ano,TPAUTOCTO,DT_NOTIFIC,EVOLUCAO)%>%
    mutate(DT_NOTIFIC = as.Date(DT_NOTIFIC)) %>% 
    mutate(mes_ano = format(DT_NOTIFIC, "%m/%Y")) %>% 
    mutate(mes=format(DT_NOTIFIC, "%m"))%>%
    group_by(mes_ano, mun)%>%count()%>%
    dplyr::rename(casos_chik=freq)%>%
    dplyr::select(ano,TPAUTOCTO,EVOLUCAO,mes)%>%
    group_by(ano)%>%
    dfSummary(style='multiline', graph.col = FALSE)

```
## populacao afetada
```{r}
dado<-zika%>%
  dplyr::select(mun)%>%
   group_by(mun)%>%
   count()%>%
   dplyr::rename(casos=freq)

dado%>%
  knitr::kable(.,"simple")
```


```{r}
x<-zika%>%
   dplyr::select(mun,populacao)%>%
   group_by(mun)%>%
   dplyr::summarise_at(c("populacao"), sum, na.rm = TRUE)%>%mutate(populacao= round(((populacao/4)),3))

```



```{r}
zika%>%
   dplyr::filter(ano==2019)%>%
   dplyr::select(mun,populacao)%>%
   dplyr::summarise_at(c("populacao"), sum, na.rm = TRUE)#%>% mutate(populacao= round(((populacao/4)),3))
```


```{r}
dado%>%
  dplyr::select(mun,casos)%>%
  left_join(x%>%dplyr::select(mun,populacao),by = c('mun' = 'mun'))%>%
    mutate(tx_zika= round(((casos/populacao)*100),3))%>%
   knitr::kable(.,"simple")

```

# casos zika geral e autóctones
```{r}
zk<-base_analise_ha_v2%>%dplyr::select(mun,ano,zika_conf)%>%
 dplyr::filter(zika_conf>0)%>%
 left_join(zk_autoctone%>%dplyr::select(mun,zk_auto,ano),by = c('mun' = 'mun', 'ano'='ano'))%>%  
 dplyr::select(mun,ano,zika_conf,zk_auto)%>%
  left_join(bahia_pop_long%>%dplyr::select(mun,ano,regiao.de.saude,macrorregiao,popporte,IDH_2015,IDH,bioma_2014,tipologia),by = c('mun' = 'mun', 'ano'='ano'))  

```

```{r}
base_analise_ha_v2%>%dplyr::select(mun,ano,zika_conf,tipologia,semiarido,IDH,bioma_2014)%>%
 dplyr::filter(zika_conf>0)%>%
 dfSummary(style='multiline', graph.col = FALSE)
```


```{r}
base_analise_ha_v2%>%dplyr::select(mun,ano,zika_conf,tipologia,semiarido)%>%
 dplyr::filter(zika_conf>0)%>%
 group_by(ano)%>%  
 dfSummary(style='multiline', graph.col = FALSE)
```
```{r}
base_aux<-base_analise_ha_v2%>%dplyr::select(mun,ano,zika_conf)%>%
 dplyr::filter(zika_conf>0)%>%
 left_join(indicadores_ba%>%dplyr::select(1:2,11,21,26),by = c('mun' = 'mun', 'ano'='ano'))
   
 
table(base_aux$tx_cadunico_tot_pes_pob_ext>0.5)
```

```{r}
count(base_aux$tx_cadunico_tot_pes_pob_ext==0.7)
```

## Localização dos casos autóctones

```{r}
zk%>%
dplyr::select(macrorregiao,zk_auto,zika_conf)%>%
 group_by(macrorregiao)%>%  
 dplyr::summarise_at(c("zk_auto", "zika_conf"), sum, na.rm = TRUE)%>%
 mutate(percent=round((zk_auto*100)/zika_conf),3)%>%
 sort_asc(percent,macrorregiao)%>%
 knitr::kable(.,"simple") 
```
```{r}
zk%>%
dplyr::select(regiao.de.saude,macrorregiao,zk_auto,zika_conf)%>%
 group_by(regiao.de.saude)%>%  
 dplyr::summarise_at(c("zk_auto", "zika_conf"), sum, na.rm = TRUE)%>%
 mutate(percent=round((zk_auto*100)/zika_conf),3)%>%
 sort_asc(percent,zk_auto,regiao.de.saude)%>%
 knitr::kable(.,"simple") 
```

```{r}
zk%>%
dplyr::select(regiao.de.saude,macrorregiao,zk_auto,zika_conf)%>%
 group_by(macrorregiao,regiao.de.saude)%>%  
 dplyr::summarise_at(c("zk_auto", "zika_conf"), sum, na.rm = TRUE)%>%
 mutate(percentual=round((zk_auto*100)/zika_conf),3)%>%
 sort_asc(percentual,macrorregiao,regiao.de.saude)%>%
ggplot(aes(x = macrorregiao,
             y = regiao.de.saude, 
             size=percentual)) +
  geom_point()+
  theme_bw() + 
  theme(axis.ticks.length = unit(-0.25, "cm"), 
        axis.ticks.margin = unit(0.5, "cm"))+
  theme(axis.title = element_text(size = 10),
        axis.text = element_text(size = 4))

ggsave("/cloud/project/binomial/bases finais/zk_auto_conf_mers.jpg")

```

```{r}
png("/cloud/project/binomial/bases finais/zk_auto_conf_macro.jpg") 

p<-zk%>%
dplyr::select(ano,macrorregiao,regiao.de.saude,zk_auto,zika_conf)%>%
 group_by(ano,macrorregiao,regiao.de.saude)%>%  
 dplyr::summarise_at(c("zk_auto", "zika_conf"), sum, na.rm = TRUE)%>%
 sort_asc(macrorregiao, regiao.de.saude, zk_auto,zika_conf)%>%
 dplyr::select(ano,macrorregiao,regiao.de.saude,zk_auto,zika_conf)%>%
  gather('variavel','casos',zika_conf,zk_auto) %>% 
  mutate(variavel = fct_reorder(variavel, casos,.desc = TRUE)) %>%
  ggplot(aes(x=casos, y=macrorregiao, fill=variavel)) +
    geom_boxplot(alpha=0.2)+
    theme_ipsum() +
    xlab(" Casos")+
    ylab("Macrorregião")+
    theme(axis.text.y=element_text(size=5),axis.text.x = element_text(size=5)
        )+facet_wrap(~variavel)+
  theme_bw() + 
  theme(axis.ticks.length = unit(-0.25, "cm"), 
        axis.ticks.margin = unit(0.5, "cm"))+
  theme(axis.title = element_text(size = 10),
        axis.text = element_text(size = 4)) +
  plot_layout(guides='collect') &
theme(legend.position='none')

print(p)
dev.off()

p
```

```{r}
png("/cloud/project/binomial/bases finais/zk_auto_conf_rs.jpg") 

p<-zk%>%
dplyr::select(ano,macrorregiao,regiao.de.saude,zk_auto,zika_conf)%>%
 group_by(ano,macrorregiao,regiao.de.saude)%>%  
 dplyr::summarise_at(c("zk_auto", "zika_conf"), sum, na.rm = TRUE)%>%
 sort_asc(macrorregiao, regiao.de.saude, zk_auto,zika_conf)%>%
 dplyr::select(ano,macrorregiao,regiao.de.saude,zk_auto,zika_conf)%>%
  gather('variavel','casos',zika_conf,zk_auto) %>% 
  mutate(variavel = fct_reorder(variavel, casos,.desc = TRUE)) %>%
  ggplot(aes(x=casos, y=regiao.de.saude, fill=variavel)) +
    geom_boxplot(alpha=0.2)+
    theme_ipsum() +
    xlab(" Casos")+
    ylab("Região de Saúde")+
    theme(axis.text.y=element_text(size=5),axis.text.x = element_text(size=5)
        )+facet_wrap(~variavel)+
  theme_bw() + 
  theme(axis.ticks.length = unit(-0.25, "cm"), 
        axis.ticks.margin = unit(0.5, "cm"))+
  theme(axis.title = element_text(size = 10),
        axis.text = element_text(size = 4)) +
  plot_layout(guides='collect') &
theme(legend.position='none')

print(p)
dev.off()
p

```

