---
title: "Análise Descritiva Arboviroses 2016-2019"
output:
  word_document:
    toc: yes
  html_document:
    highlight: tango
    lib_dir: libs
    number_sections: yes
    theme: yeti
    toc: yes
    toc_float:
      collapse: yes
---

```{r setup,include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, comment = '', warning = FALSE)
```

```{r}
library(data.table)
library(tidyverse)
library(dplyr)
library(read.dbc)
library(foreign)
library(dplyr)
require("stringr")
require(summarytools)
library(rapportools)
source("http://pcwww.liv.ac.uk/~william/R/crosstab.r")
```

<!-- # Leitura da base -->
```{r}
library(tibble)
library(readxl)
```

```{r}
#setwd("C:/Users/Visitante/Downloads/SINAN/dados_dengue/raw/")
```

```{r}
#nome.arquivo<-"Arboviroses casos confirmados notificados Bahia 2016 - 2019"
#load("G:/backup_maira/SINAN/analisebruno/arboviroses.Rdata")
#load("/cloud/project/fe_dataset_arboviroses_fase1.RData")
load("/cloud/project/fe_base de casos corrigidas/fe_dataset_arboviroses_fase1.RData")
load("/cloud/project/binomial/bases finais/base_analise_ha_v2.RData")
load("/cloud/project/binomial/bases finais/bahia_pop_long.RData")
load("/cloud/project/binomial/scrpits/autoctone/data_arbo_autoc_att_vcasos_e_tx.RData")
load("/cloud/project/binomial/bases finais/indicadores_ba.RData")
```

```{r}
dng<-fe_dengue_conf
zk<-fe_zika_conf
chik<-fe_chik_conf
```

# Estrutura da base

## dengue
```{r}
#names(fe_dengue_conf)
```
# Casos confirmados por ano


```{r}
library(expss) #Tables with Labels in R
tab_conf<-base_analise_ha_v2%>%dplyr::select(ano,dg_conf)%>%
 dplyr::filter(dg_conf>0)%>%
 group_by(ano)%>%  
 dplyr::summarise_at(c("dg_conf"), sum, na.rm = TRUE)%>%
 sort_asc(ano,dg_conf)%>%
 knitr::kable(.,"simple")

```
# casos suspeitos por ano
 
```{r}
fe_dengue_susp_muni%>%
 dplyr::filter(casos_dengue>0)%>%
 group_by(NU_ANO)%>%  
 dplyr::summarise_at(c("casos_dengue"), sum, na.rm = TRUE)%>%
 sort_asc(NU_ANO,casos_dengue)

```
```{r}
base_analise_ha_v2%>%dplyr::select(ano,dg_conf,dg_susp)%>%
 dplyr::filter(dg_conf>0|dg_susp>0)%>%
 group_by(ano)%>%  
 dplyr::summarise_at(c("dg_conf","dg_susp"), sum, na.rm = TRUE)%>%
 mutate(percent_conf=round((dg_conf/dg_susp)*100,2))%>%  
 sort_asc(ano,dg_conf,dg_susp)%>%
 knitr::kable(.,"simple")
```


# Desfecho
1-Cura
2- Óbito por zk
3- Óbito por outras causas
4 – Óbito em investigação
9- Ignorado

```{r}
library("dplyr")

a<- fe_dengue_conf %>%
    dplyr::select(MUN_RESI,NU_ANO,TPAUTOCTO,DT_NOTIFIC,EVOLUCAO)%>%
    mutate(DT_NOTIFIC = as.Date(DT_NOTIFIC)) %>% 
    mutate(mes_ano = format(DT_NOTIFIC, "%m/%Y")) %>% 
    mutate(mes=format(DT_NOTIFIC, "%m"))%>%
    group_by(mes_ano, MUN_RESI)%>%count()

a %>%
    dplyr::rename(casos_dengue=freq)%>%
    dplyr::select(TPAUTOCTO,EVOLUCAO,mes)%>%
   dfSummary(style='multiline', graph.col = FALSE)
```

# dengue municipios ao longo dos 4 anos
 
```{r}
dg<-base_analise_ha_v2%>%dplyr::select(mun,ano,dg_conf)%>%
 dplyr::filter(dg_conf>0)%>%
 group_by(ano)

mun2016<-dg$mun[dg$ano==2016]
mun2017<-dg$mun[dg$ano==2017]
mun2018<-dg$mun[dg$ano==2018]
mun2019<-dg$mun[dg$ano==2019]
```

```{r}
uni_16_17<-intersect(mun2016,mun2017)
uni_161718<-intersect(uni_16_17,mun2018)
uni_16171819<-intersect(uni_161718,mun2019)
uni_16171819
```



```{r}
dg_cocirc<-bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::filter(ano==2016)%>%
  dplyr::select(macrorregiao,regiao.de.saude, mun)%>%
# dplyr::group_by(macrorregiao,regiao.de.saude)%>%
sort_desc(macrorregiao,regiao.de.saude)

dg_cocirc%>%
  knitr::kable(.,"simple")
```

```{r}
dg_cocirc%>%
dplyr::select(macrorregiao,regiao.de.saude)%>%
#group_by(macrorregiao)%>% 
dfSummary(style='multiline', graph.col = FALSE)


```
```{r}
dg_cocirc%>%
dplyr::select(macrorregiao)%>%
count()#%>%sort_desc()
```
```{r}
dg_cocirc%>%
dplyr::select(regiao.de.saude)%>%
count()#%>%sort_desc(freq)
```


## caracteristicas municipios
```{r}
bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::filter(ano==2016)%>%
  dplyr::select(mun,popporte,IDH,bioma_2014,newtipology,tipologia)%>%
  knitr::kable(.,"pipe",align = "c")

```

```{r}
#bioma_2014 = c("floresta"=1, "natural não florestal"=2,"Agropecuária"=3,                             "Area não vegetada"=4, "corpos d’água"=5)

bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::filter(ano==2016)%>%
  dplyr::select(mun,popporte,IDH,bioma_2014,newtipology,tipologia)%>%
  dfSummary(style='multiline', graph.col = FALSE)
```

```{r}
load("/cloud/project/binomial/bases finais/indicadores_ba.RData")
#bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
#  dplyr::select(mun,ano)%>%
#  left_join(indicadores_ba%>%dplyr::select(1:2,11,21,26),by = c('mun' = 'mun', 'ano'='ano'))%>%
#  knitr::kable(.,"pipe",align = "c")
```


```{r}
bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
  #dplyr::select(mun,ano)%>%
  left_join(indicadores_ba%>%dplyr::select(1:2,11,21,26),by = c('mun' = 'mun', 'ano'='ano'))%>%
  dplyr::select (cadu_Ssnis,cadunico_tot_pes_pob_e_ext_pob,tx_cadunico_tot_pes_pob_ext,semiarido)%>%
  dfSummary(style='multiline', graph.col = FALSE)

```

```{r}
percent_snis<-indicadores_ba%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::filter(ano==2016)%>%
  dplyr::select(mun, pop_2015,cadu_Ssnis_2015,cadu_Ssnis)%>%
  group_by(mun)%>%
 # mutate(cadu_Ssnis=sum(cadu_Ssnis))%>%
  
  dplyr::summarise_at(c("cadu_Ssnis","pop_2015"), sum, na.rm = TRUE)%>%
  mutate(percent_Ssnis= round(((cadu_Ssnis/(pop_2015-1))*100),3))%>%# percentual
  sort_asc(percent_Ssnis,mun)

#percent_snis%>%
 # dfSummary(style='multiline', graph.col = FALSE)
#  knitr::kable(.,"simple")
```

```{r}
base_analise_ha_v2%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::select(mun, dg_conf)%>%
  group_by(mun)%>%  
  dplyr::summarise_at(c("dg_conf"), sum, na.rm = TRUE)%>%
  sort_asc(mun,dg_conf)%>%
  left_join(bahia_pop_long %>%
              dplyr::filter(ano==2016)%>%
              dplyr::select(mun,macrorregiao,regiao.de.saude,popporte,IDH,bioma_2014,newtipology,tipologia,semiarido),by = c('mun' = 'mun'))%>%
  dplyr::select(mun,macrorregiao,regiao.de.saude,popporte,IDH,bioma_2014,tipologia,dg_conf)%>%
  dplyr::mutate(tipologia = case_when(
                              tipologia== 1 ~ 'Rural',
                              tipologia== 2 ~ 'Urbano'))%>%
  dplyr::mutate(bioma_2014 = case_when(
                              bioma_2014== 1 ~ 'Floresta',
                              bioma_2014== 2 ~ 'Natural não florestal', 
                              bioma_2014== 3 ~ 'Agropecuária', 
                              bioma_2014== 4 ~ 'Area não vegetada',
                              bioma_2014== 5 ~ 'Corpos d’água'))%>%
  sort_desc(macrorregiao,regiao.de.saude,dg_conf)%>%
  knitr::kable(.,"simple")
  
```

```{r}
library("ggplot2")
library("scales")
library("viridis")
library("hrbrthemes")
base_analise_ha_v2%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::select(mun,ano,tx_vacina,tx_G12A,tx_fluxo,tx_cadunico_tot_pes_pob_ext)%>%
  gather('variavel','taxa',tx_vacina,tx_G12A,tx_fluxo,tx_cadunico_tot_pes_pob_ext)%>%
  mutate(variavel = fct_reorder(variavel, taxa,.desc = TRUE)) %>%
ggplot(aes(x=taxa, y=mun, fill=variavel)) +
    geom_boxplot(alpha=0.2)+
    theme_ipsum() +
    xlab(" Taxas do município")+
    ylab("Municipio")+
    theme(axis.text.y=element_text(size=5),axis.text.x = element_text(size=5)
        ) +facet_wrap(~variavel,nrow=2)
#+ theme(legend.position='none')
```
```{r}
#selecao de casos autoctones que ocorreram nos 4 anos seguidos
dg_cocirc_auto<-dg_autoctone%>%
  dplyr::filter(dg_auto>0)%>%
  dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::select(mun)%>%
  group_by(mun)%>%
  count()

names(dg_cocirc_auto)=c("mun","anos")
dg_cocirc_auto %>%
  dplyr::filter(anos==4)


```

```{r}

dg_autoctone%>% 
  dplyr::filter(mun%in%dg_cocirc_auto$mun)%>%
  dplyr::select(mun,ano,dg_auto)%>%
  group_by(mun,ano)%>%
 dplyr::summarise_at(c("dg_auto"), sum, na.rm = TRUE)%>%
  sort_asc(mun,ano,dg_auto)%>%
  knitr::kable(.,"simple")
```

```{r}
base_analise_ha_v2%>% 
  dplyr::filter(mun%in%dg_cocirc_auto$mun)%>%
  dplyr::select(mun,ano,tx_dg_auto)%>%
  group_by(mun,ano)%>%
 dplyr::summarise_at(c("tx_dg_auto"), sum, na.rm = TRUE)%>%
 sort_asc(mun,ano,tx_dg_auto)%>%
  knitr::kable(.,"simple")

```


```{r}
municipios<-dg_cocirc_auto$mun

casos_dg_conf_auto_cocirc<-base_analise_ha_v2%>% 
  dplyr::select(mun,ano,dg_conf,populacao)%>%
  dplyr::filter(mun%in%municipios)%>%
    left_join(dg_autoctone%>%dplyr::select(mun, ano, dg_auto),by = c('mun' = 'mun','ano'='ano'))%>%
  dplyr::select(mun,ano,dg_conf,dg_auto)%>%
  group_by(mun,ano)%>%
 dplyr::summarise_at(c("dg_conf","dg_auto"), sum, na.rm = TRUE)%>%
 sort_asc(mun,ano)
```

```{r}
dados<-base_analise_ha_v2%>% 
  dplyr::select(mun,ano,dg_conf,populacao)%>%
  dplyr::filter(mun%in%municipios)%>%
  left_join(dg_autoctone%>%dplyr::select(mun, ano, dg_auto),by = c('mun' = 'mun','ano'='ano'))%>%
  dplyr::select(mun,ano,dg_conf,dg_auto,populacao)%>%
  group_by(mun,ano)%>%
  mutate(tx_dg=round(dg_conf/populacao,2))%>%
  mutate(tx_auto=round(dg_auto/populacao,2))%>%
  mutate(percent=round((dg_auto/dg_conf)*100,2))%>%
  dplyr::select(mun,ano,tx_dg,tx_auto,percent)%>%
  dplyr::summarise_at(c("tx_dg","tx_auto","percent"), sum, na.rm = TRUE)%>%
  sort_asc(mun,ano)%>%
  dplyr::filter(percent>100)

unique(dados$mun)
```


```{r}
library("patchwork")

q1<-base_analise_ha_v2%>% 
  dplyr::select(mun,ano,dg_conf,populacao)%>%
  dplyr::filter(mun%in%municipios)%>%
  left_join(dg_autoctone%>%dplyr::select(mun, ano, dg_auto),by = c('mun' = 'mun','ano'='ano'))%>%
  dplyr::select(mun,ano,dg_conf,dg_auto,populacao)%>%
  group_by(mun,ano)%>%
  mutate(tx_dg=round(dg_conf/populacao,2))%>%
  mutate(tx_auto=round(dg_auto/populacao,2))%>%
  mutate(percent=round((dg_auto/dg_conf)*100,2))%>%
  dplyr::select(mun,ano,tx_dg,tx_auto,percent)%>%
  dplyr::summarise_at(c("tx_dg","tx_auto","percent"), sum, na.rm = TRUE)%>%
 sort_asc(mun,ano)%>%
 gather('variavel','casos',tx_dg,tx_auto) %>% 
  mutate(variavel = fct_reorder(variavel, casos,.desc = TRUE))%>%
 ggplot(aes(x=casos, y=mun, fill=variavel)) +
    geom_boxplot(alpha=0.2)+
    theme_ipsum() +
    xlab(" Casos")+
    ylab("Municipios")+
    theme(axis.text.y=element_text(size=5),axis.text.x = element_text(size=5)
        )+facet_wrap(~variavel)
 

q1 + 
  theme_bw() + 
  theme(axis.ticks.length = unit(-0.25, "cm"), 
        axis.ticks.margin = unit(0.5, "cm"))+
  theme(axis.title = element_text(size = 10),
        axis.text = element_text(size = 4))

q1+ theme_bw()+plot_layout(guides='collect') &
theme(legend.position='none')
```



```{r}
bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::filter(ano==2016)%>%
  dplyr::select(regiao.de.saude,macrorregiao,popporte,IDH_2015,IDH,bioma_2014,tipologia)%>%
  dfSummary(style='multiline', graph.col = FALSE)
```

```{r}
dengue<-indicadores_ba%>%
  dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::select(mun,ano,ibge,populacao)%>%
  left_join(fe_dengue_conf%>%dplyr::select(ID_MN_RESI,NU_ANO,TPAUTOCTO,DT_NOTIFIC,EVOLUCAO),by = c('ibge' = 'ID_MN_RESI','ano'='NU_ANO'))

base_aux<-dengue%>%
   mutate(DT_NOTIFIC = as.Date(DT_NOTIFIC)) %>% 
    mutate(mes_ano = format(DT_NOTIFIC, "%m/%Y")) %>% 
    mutate(mes=format(DT_NOTIFIC, "%m"))%>%
    group_by(mes_ano, mun)%>%count()

#names(base_aux)[10]<-c("casos")

base_aux%>%
#    dplyr::rename(casos_dengue=freq)%>%
#    dplyr::select(TPAUTOCTO,EVOLUCAO,mes)%>%
    dfSummary(style='multiline', graph.col = FALSE)
```
### Autóctones


```{r}
library(dplyr)
library(magrittr)

#dengue%>%
#    dplyr::select(mun,ano,TPAUTOCTO,DT_NOTIFIC,EVOLUCAO)%>%
#    mutate(DT_NOTIFIC = as.Date(DT_NOTIFIC)) %>% 
#    mutate(mes_ano = format(DT_NOTIFIC, "%m/%Y")) %>% 
#    mutate(mes=format(DT_NOTIFIC, "%m"))%>%
#    group_by(mes_ano, mun)%>%count()%>%
#   dplyr::rename(casos_dengue=freq)%>%
#   dplyr::select(ano,TPAUTOCTO,EVOLUCAO,mes)%>%
#   dplyr::group_by(ano)%>%
#  dfSummary(style='multiline', graph.col = FALSE)
```



## populacao afetada
```{r}
dado<-dengue%>%
  dplyr::select(mun)%>%
   group_by(mun)%>%
   count()#%>% dplyr::rename(casos=freq)

dado%>%
  knitr::kable(.,"simple")
```


```{r}
x<-dengue%>%
   dplyr::select(mun,populacao)%>%
   group_by(mun)%>%
   dplyr::summarise_at(c("populacao"), sum, na.rm = TRUE)%>%mutate(populacao= round((((populacao-1)/4)),3))

x%>%
  knitr::kable(.,"simple")
```



# casos dg  geral e autóctones
```{r}
dg_b<-base_analise_ha_v2%>%dplyr::select(mun,ano,dg_conf)%>%
 dplyr::filter(dg_conf>0)%>%
 left_join(dg_autoctone%>%dplyr::select(mun,dg_auto,ano),by = c('mun' = 'mun', 'ano'='ano'))%>%  
 dplyr::select(mun,ano,dg_conf,dg_auto)%>%
  left_join(bahia_pop_long%>%dplyr::select(mun,ano,regiao.de.saude,macrorregiao,popporte,IDH_2015,IDH,bioma_2014,tipologia),by = c('mun' = 'mun', 'ano'='ano'))  

```

```{r}
base_analise_ha_v2%>%dplyr::select(mun,ano,dg_conf,tipologia,semiarido,IDH,bioma_2014)%>%
 dplyr::filter(dg_conf>0)%>%
 dfSummary(style='multiline', graph.col = FALSE)
```


```{r}
base_analise_ha_v2%>%dplyr::select(mun,ano,zika_conf,tipologia,semiarido)%>%
 dplyr::filter(zika_conf>0)%>%
 group_by(ano)%>%  
 dfSummary(style='multiline', graph.col = FALSE)
```
```{r}
base_aux<-base_analise_ha_v2%>%dplyr::select(mun,ano,zika_conf)%>%
 dplyr::filter(zika_conf>0)%>%
 left_join(indicadores_ba%>%dplyr::select(1:2,11,21,26),by = c('mun' = 'mun', 'ano'='ano'))
   
 
table(base_aux$tx_cadunico_tot_pes_pob_ext>0.5)
```

```{r}
#dplyr::count(base_aux$tx_cadunico_tot_pes_pob_ext==0.7)
```

