---
title: "Cobertura vacianal Febre Amarela (09/09/2022)"
output: 
  html_document:
    code_folding: hide
    highlight: tango
    lib_dir: libs
    number_sections: yes
    theme: yeti
    toc: yes
    toc_float:
      collapse: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, comment = '', warning = FALSE)
```

```{r}
library(dplyr)
library(readxl)
library(data.table)
library(abjutils)
library(stringr)
library(foreign)
library(tidyr)
```


```{r}
require(foreign)
require(ggplot2)
require(MASS)
```


```{r}
#setwd("/cloud/project/teste PCR/base long/Hipoteses")
load("/cloud/project/binomial/scrpits/scrpit vacinas/data_arbo_long_v4.RData")
load("/cloud/project/bases usadas/var_IBGE_ba.RData")
```


```{r}
library(haven)
data_cov<- read_dta("/cloud/project/bases usadas/Covariaveis_Censo-IBGE_DATASUS_MDS_2004-2015_Preliminar.dta")%>% dplyr::filter(year==2015 & (as.numeric(ibge_code)%in% var_IBGE_ba) ) %>%dplyr::select(1,2,7,8,14,15,19,20,21,22)

data_cov$mun<-abjutils::rm_accent(data_cov$mun)
data_cov$ibge_code<-as.numeric(data_cov$ibge_code)

data_cov$mun<-gsub("DIAS D'AVILA", "DIAS D AVILA", data_cov$mun)
data_cov$mun<-replace(data_cov$mun, data_cov$mun=="Barrocas (BA)","BARROCAS")
data_cov$mun<-replace(data_cov$mun, data_cov$mun=="Luis Eduardo Magalhaes (BA)","LUIS EDUARDO MAGALHAES")

data_cov$popporte[data_cov$mun=="LUIS EDUARDO MAGALHAES"]<-"Pequeno Porte II"
data_cov$popporte[data_cov$mun=="BARROCAS"]<-"Pequeno Porte I"

#Em segunda oportunidade, o município de Barrocas foi criado pela Lei Estadual nº 7.620, de 30 de março de #2000, sendo, juntamente com Luís Eduardo Magalhães, um dos municípios mais jovens do estado da Bahia.[5] #Localiza-se a 185 km da Capital do Estado.
#sinalizado mun_5507 com 0. não coberto nos censos

#mun<-data_cov$mun
#munis<-data_arbo_long_v5$mun             
#diff<-setdiff(mun,munis)
```


```{r}
#Cobertura por Município e Imuno
#http://tabnet.datasus.gov.br/cgi/deftohtm.exe?pni/CNV/CPNIBA.def
#Fonte: Programa Nacional de Imunizações
#Notas:
#Data de atualização dos dados: 04/09/2019
#Os dados apresentados em 2013 se referem à soma dos seguintes dados:
#Até Junho de 2013: dados do API DOS
#A partir de Julho de 2013: APIWEB + SIPNI Web  (exceção UFs: AC, CE, DF , GO , MS, MT, PA, PR, RJ, SE, MA e #TO por digitação duplicada)
#Base de dados do ano de 2013 foi encerrada em 23/03/2015.
#Doses aplicadas durante o MRC (pneumo 10 e meningo C) e Multivacinação
#2014:
#Dados do ano de 2014 são parciais. Referem-se ao recebimento das informações do APIWEB + SIPNI até a data de 23/03/2015.
library(readxl)
data_vacina <- read_excel("/cloud/project/bases usadas/cobertura_vacinal_2015-2019.xlsx")[1:417,]#sem total
data_vacina$mun<-toupper(abjutils::rm_accent(data_vacina$mun))
data_vacina$mun<-gsub("DIAS D'AVILA", "DIAS D AVILA", data_vacina$mun)
data_vacina$IBGE_6<-as.numeric(data_vacina$IBGE_6)
data_vacina$`006_FA_2015`<-as.numeric(data_vacina$`006_FA_2015`)
data_vacina$`006_FA_2016`<-as.numeric(data_vacina$`006_FA_2016`)
data_vacina$`006_FA_2017`<-as.numeric(data_vacina$`006_FA_2017`)
data_vacina$`006_FA_2018`<-as.numeric(data_vacina$`006_FA_2018`)
data_vacina$`006_FA_2019`<-as.numeric(data_vacina$`006_FA_2019`)

names(data_vacina)<-c( "IBGE_6","mun","FA_2015","FA_2016","FA_2017","FA_2018","FA_2019")
#data_vacina <- data_vacina%>% mutate(across(where(is.character), as.numeric))

data_cov<-data_vacina%>%dplyr::select(1:3)%>%
  left_join(data_cov, by = c('mun' = 'mun','IBGE_6'='ibge_code'))


data_vacina_FA_long<-data_vacina %>% dplyr::select(mun,contains('FA_'))%>% 
  pivot_longer(cols = -mun,names_to = 'variavel', values_to = 'vacina')%>% 
  mutate(ano=as.numeric(str_extract(variavel, "[[:digit:]]+")))%>%
  dplyr::select(mun,ano,vacina,everything())%>%
  dplyr::select(-variavel)%>%
  mutate(tx_vacina= vacina/100)%>% # por ha. Variável vacina está por 100 ha.
  mutate(tx_vacina_1= round((vacina/100)*100000,3))%>% #por 100 mil ha
  dplyr::filter(ano>2015)

vacina_fa_ba<-data_vacina_FA_long
#save(vacina_fa_ba,file="/cloud/project/binomial/bases finais/vacina_fa_ba.RData")

#save(data_vacina, data_vacina_FA_long,file="/cloud/project/binomial/bases finais/data_vacina_FA.RData")
```

```{r}
library(readxl)
data_atlas <- read_excel("/cloud/project/bases usadas/data_atlas.xlsx")%>%dplyr::select(1,8)
names(data_atlas)<-c("mun","cadu_Ssnis_2015")
data_atlas$mun<-toupper(abjutils::rm_accent(data_atlas$mun))
data_atlas$mun<-gsub("DIAS D'AVILA", "DIAS D AVILA", data_atlas$mun)

data_cov<-data_cov%>%
  left_join(data_atlas, by = c('mun' = 'mun'))%>%dplyr::rename(vacina="FA_2015")



#save(data_cov,file="/cloud/project/binomial/bases finais/data_cov.RData")
```
Elaboração: Atlas do Desenvolvimento Humano no Brasil. Pnud Brasil, Ipea e FJP, 2020.

Fontes: dados do IBGE e de registros administrativos, conforme especificados nos metadados disponíveis aqui.

FAIXAS DE DESENVOLVIMENTO HUMANO

MUITO ALTO 0,800 - 1,000

ALTO 0,700 - 0,799

MÉDIO 0,600 - 0,699

BAIXO 0,500 - 0,599

MUITO BAIXO 0,000 - 0,499

```{r}
data_ba_1<-data_cov%>%dplyr::select(mun,idhm,cadu_Ssnis_2015,desemprego,pobres,cobertbf,vacina)%>%
  dplyr::rename('IDH_2015'=idhm)

var_elimin<-c("IDH_2010","interp_AGUA_ESGOTO2015","interp_IDHM2015","interp_GINI2015")


#var_elimin<-c("IDH_2010","interp_IDHM2015","interp_GINI2015")
#data_arbo_long_v5<-data_arbo_long_v4 %>% dplyr::select(-var_elimin)%>%
#  left_join(data_ba_1, by = c('mun' = 'mun'))%>%
#  dplyr::select(mun,ano,dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf,everything#())

data_ba_1$IDH_2015[data_ba_1$mun=="LUIS EDUARDO MAGALHAES"]<-0.716
data_ba_1$IDH_2015[data_ba_1$mun=="BARROCAS"]<-0.610


#save(data_ba,file = "/cloud/project/binomial/dados_finais/data_ba.RData")
#save(data_ba_1,file = "/cloud/project/binomial/bases finais/data_ba_1.RData")

```


