---
title: "Descritiva Arboviroses Bahia (parte 5) - Atualizado (2022)" 
date: "`r Sys.Date()`"
output: 
  html_document:
    highlight: tango
    #number_sections: yes
    theme: yeti
    toc: yes
    toc_float:
      collapse: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, comment = '', warning = FALSE, fig.width = 20, fig.height = 12)
```


```{r include = FALSE}
library(dplyr)
library(tidyverse)
library(knitr)
library(zoo)
library(ggplot2)
library(sf)
library(RColorBrewer)
#load('fe_datasets_municipio_att.RData')
load("/cloud/project/fe_datasets_municipio_att.RData")
#load("fe_dataset_arboviroses_fase1.RData")
load("/cloud/project/fe_dataset_arboviroses_fase1.RData")
```

# Sorotipo (dengue)

```{r include=FALSE}
fe_dengue_conf = fe_dengue_conf %>% mutate(SOROTIPO = case_when(
                               SOROTIPO == 1 ~ 'DEN 1',
                               SOROTIPO == 2 ~ 'DEN 2', 
                               SOROTIPO == 3 ~ 'DEN 3',
                               SOROTIPO == 4 ~ 'DEN 4'))
anos = 2016:2019
```

## Tabela

```{r results='asis'}
for(ano in anos){
    base_arb = fe_dengue_conf %>% 
      filter(!is.na(SOROTIPO) & NU_ANO == ano) %>% 
      group_by(ID_MN_RESI, SOROTIPO) %>% count() %>% rename('casos' = n) %>% 
      inner_join(aux_pop %>% 
                    dplyr::select(IBGE_6, mun), by = c('ID_MN_RESI' = 'IBGE_6')) #%>% 
      # rename(pop = paste0('pop.', ano))
    
    base_arb = base_arb %>% 
      pivot_wider(names_from = SOROTIPO, values_from = casos, values_fill = 0) %>% 
      as.data.frame() %>% 
      dplyr::select(!c(ID_MN_RESI)) %>% 
      rename('Município' = mun)
    
    #base_arb = base_arb[, c('Município', sort(colnames(base_arb)[-1]))]
    
      print(kable(base_arb %>% dplyr::select(sort(colnames(base_arb))) %>% relocate('Município'), caption = paste0('Número de casos confirmados por município e sorotipo de dengue, Bahia, ', ano)))
      cat('\n')
}  
```
### Por Macrorregiao

```{r}
base_arb_rs = fe_dengue_conf %>% 
      filter(!is.na(SOROTIPO)) %>% 
      group_by(ID_MN_RESI, SOROTIPO,NU_ANO) %>% count() %>% rename('casos' = n) %>% 
      inner_join(aux_pop %>% 
                    dplyr::select(IBGE_6, mun,macrorregiao,regiao.de.saude), by = c('ID_MN_RESI' = 'IBGE_6'))

base_arb_rs = base_arb_rs %>%
      dplyr::select(macrorregiao,SOROTIPO,NU_ANO,casos)%>%
      group_by(macrorregiao,SOROTIPO,NU_ANO)%>%
      dplyr::summarise_at(c("casos"), sum, na.rm = TRUE)%>%
      sort_asc(macrorregiao,SOROTIPO,NU_ANO, casos)%>%
      pivot_wider(names_from = SOROTIPO, values_from = casos, values_fill = 0) %>% 
      as.data.frame()  %>% 
      #dplyr::select(!c(ID_MN_RESI))%>%
      rename('Ano' = NU_ANO)
  
base_arb_rs%>%
  knitr::kable(.,"simple") 
```


## Gráfico

```{r results='asis'}
for (ano in anos){

  graf_mes = fe_dengue_conf %>% filter(!is.na(SOROTIPO) & NU_ANO == ano) %>% 
        group_by(ID_MN_RESI, DT_NOTIFIC, SOROTIPO) %>% count() %>% rename('casos' = n) %>% 
        mutate('DT_NOTIFIC' = months(as.Date(DT_NOTIFIC), abbreviate = TRUE)) %>% 
        group_by(DT_NOTIFIC, SOROTIPO) %>% summarise('casos' = sum(casos)) %>% 
        mutate('DT_NOTIFIC' = factor(DT_NOTIFIC, levels = c('jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez')))
      
      fig = ggplot(graf_mes, aes(x = DT_NOTIFIC, y = casos, fill = as.factor(SOROTIPO))) +
        geom_bar(stat = "identity", position = "stack") +
        labs(title = paste0('Distribuição mensal de casos confirmados da dengue por sorotipo em ', ano), y = 'Número de casos', x = 'Mês', fill = 'Sorotipo') +
        scale_fill_manual(breaks = c('DEN 1', 'DEN 2', 'DEN 3', 'DEN 4'), values = c('LightGreen', 'darkorange', 'brown1', 'cornflowerblue')) +
        theme_minimal() +
        theme(axis.text.x = element_text(size = 16), 
                axis.title.x = element_text(size = 18),
                axis.text.y = element_text(size = 16), 
                axis.title.y = element_text(size = 18),
                legend.text = element_text(size = 16),
                title = element_text(size = 18))
        print(fig)
        cat('\n\n')

}
```

## Mapa

```{r include=FALSE}
shp_bahia = sf::st_read('/cloud/project/descritiva/fe_descritiva_att/29MUE250GC_SIR.shp')
```

```{r results='asis'}
for (ano in anos){
  base_arb = fe_dengue_conf %>% filter(!is.na(SOROTIPO) & NU_ANO == ano) %>% 
    group_by(ID_MN_RESI, SOROTIPO) %>% count() %>% select(!n) %>% 
    inner_join(aux_pop %>% select(IBGE_6, IBGE_7), by = c('ID_MN_RESI' = 'IBGE_6')) %>% 
    mutate(IBGE_7 = as.character(IBGE_7))
  
  duplo_sorotipo = which(duplicated(base_arb$ID_MN_RESI) == TRUE)
  
  mun_duplo_sorotipo = unique(base_arb$ID_MN_RESI[duplo_sorotipo])
  
  for(mun in mun_duplo_sorotipo){
    combine_sorotipo = ''
    indices_duplo_sorotipo = which(base_arb$ID_MN_RESI == mun)
    for(s in base_arb$SOROTIPO[indices_duplo_sorotipo])
      combine_sorotipo = paste0(combine_sorotipo, ' ', s)
  
    combine_sorotipo = str_trim(combine_sorotipo)
    
    base_arb$SOROTIPO[indices_duplo_sorotipo] = combine_sorotipo
  }
  
  base_arb = base_arb[!duplicated(base_arb), ]

  base_mapa = left_join(shp_bahia, base_arb, by = c('CD_GEOCODM' = 'IBGE_7'))
  
  base_mapa$SOROTIPO[is.na(base_mapa$SOROTIPO)] = 'Sem registro'

  breaks_map = sort(unique(base_mapa$SOROTIPO))
  
  fig = ggplot(base_mapa, aes(fill = SOROTIPO)) +
        geom_sf() +
        labs(title = paste0('Detecção dos sorotipos de dengue, por município, Bahia, em ', ano), fill = 'Sorotipo') +
        scale_fill_manual(breaks = breaks_map, values = c(brewer.pal(n = length(breaks_map) - 1, name = "Set2"), 'gray')) +
        theme(axis.text.x = element_text(size = 16), 
                axis.title.x = element_text(size = 18),
                axis.text.y = element_text(size = 16), 
                axis.title.y = element_text(size = 18),
                legend.text = element_text(size = 16),
                title = element_text(size = 18))
    print(fig)
    cat('\n\n')
}
```

# Indicadores epidemiológicos - Cocirculação de arboviroses

## Gráfico

```{r results='asis'}
for (ano in anos){
  #cols = colnames(aux_pop)[str_detect(colnames(aux_pop), pattern = paste0('incid_', ano))]
  
  base_map = aux_pop %>% 
    select(IBGE_7, contains(paste0('incid_conf_', ano))) %>% 
    pivot_longer(cols = !IBGE_7, names_to = 'variavel', values_to = 'metrica') %>%  
    mutate(IBGE_7 = as.character(IBGE_7))
  
  base_map$variavel[str_detect(base_map$variavel, pattern = '^dg')] = 'DEN'
  base_map$variavel[str_detect(base_map$variavel, pattern = '^zk')] = 'ZIKA'
  base_map$variavel[str_detect(base_map$variavel, pattern = '^chik')] = 'CHIK'
  
  base_map_arb_ci_acima_100 = base_map %>% group_by(IBGE_7) %>% 
    summarise('soma' = sum(metrica, na.rm = TRUE)) %>% 
    filter(soma > 300) %>% 
    mutate('ci_100' = 'DEN ZIKA CHIK > 100') %>% select(IBGE_7, ci_100)
  
  base_map = base_map %>% filter(!(IBGE_7 %in% base_map_arb_ci_acima_100$IBGE_7))
  
  base_map_ci = base_map %>% group_by(IBGE_7) %>% summarise('metrica' = max(metrica, na.rm = TRUE))
  
  base_map_ci_abaixo_100 = base_map_ci %>% 
    filter(metrica <= 100) %>% 
    mutate('ci_100' = '<= 100') %>% select(IBGE_7, ci_100)
  
  base_final = rbind(base_map_arb_ci_acima_100, base_map_ci_abaixo_100)
  
  base_map_ci_acima_100 = base_map %>% 
    filter(!(IBGE_7 %in% c(base_map_ci_abaixo_100$IBGE_7, base_map_arb_ci_acima_100$IBGE_7))) %>% 
    mutate('ci_100' = ' > 100')
    
  id_municip_acima_100 = unique(base_map_ci_acima_100$IBGE_7)
  
  for(id in id_municip_acima_100){
    combine_arb = ''
    arb_100 = base_map_ci_acima_100 %>% 
      filter(IBGE_7 == id & metrica > 100) %>% select(variavel)
    for(s in arb_100$variavel)
      combine_arb = paste0(combine_arb, ' ', s)
    
    combine_arb = str_trim(combine_arb)
    
    base_map_ci_acima_100$ci_100[which(base_map_ci_acima_100$IBGE_7 == id)] = paste0(combine_arb, ' > 100')
  }
  
  base_map_ci_acima_100 = base_map_ci_acima_100[!duplicated(base_map_ci_acima_100$IBGE_7), ] %>% 
    select(IBGE_7, ci_100)
  
  base_final = shp_bahia %>% 
    left_join(rbind(base_final, base_map_ci_acima_100), by = c('CD_GEOCODM' = 'IBGE_7'))
  
  breaks_map = sort(unique(base_final$ci_100))
  
  fig = ggplot(base_final, aes(fill = ci_100)) +
        geom_sf() +
        labs(title = paste0('Cocirculação das arboviroses, por município, Bahia, em ', ano), fill = 'Incidência arboviroses') +
        scale_fill_manual(breaks = breaks_map, values = c('gray', brewer.pal(n = length(breaks_map) - 1, name = "Set2"))) +
        theme(axis.text.x = element_blank(), 
          axis.text.y = element_blank(), 
          legend.text = element_text(size = 16),
          title = element_text(size = 18))
    print(fig)
    cat('\n\n')
  
}  
```

# Cenário de cocirculação de arboviroses nos municípios da Bahia

```{r results='asis'}
for(ano in anos){
    
    base = aux_pop %>% 
      select(macrorregiao, mun, IBGE_6, contains(paste0('incid_conf_', ano)),
                                contains(paste0('pop.', ano))) %>% 
      rename('Incidência Dengue' = paste0('dg_incid_conf_', ano), 
             'Incidência Zika' = paste0('zk_incid_conf_', ano),
             'Incidência Chikungunya' = paste0('chik_incid_conf_', ano)) %>% 
      left_join(fe_dengue_conf_muni %>% filter(NU_ANO == ano) %>% 
                  as.data.frame() %>% select(ID_MN_RESI, casos_dengue), 
                  by = c('IBGE_6' = 'ID_MN_RESI')) %>% 
      left_join(fe_zika_conf_muni %>% filter(NU_ANO == ano) %>% 
                  as.data.frame() %>% select(ID_MN_RESI, casos_zika), 
                by = c('IBGE_6' = 'ID_MN_RESI')) %>% 
      left_join(fe_chik_conf_muni %>% filter(NU_ANO == ano) %>% 
                  as.data.frame() %>% select(ID_MN_RESI, casos_chik),
                by = c('IBGE_6' = 'ID_MN_RESI'))
    
  base = base %>% arrange(macrorregiao) %>% 
    mutate_if(is.numeric, coalesce, 0) %>% 
    rename('Município' = mun, 'Populacao' = paste0('pop.', ano)) %>% 
    as.data.frame() %>% select(!c(IBGE_6))
  
  base_macro = base %>% select(!c('Município')) %>% 
    group_by(macrorregiao) %>% 
      summarise_if(is.numeric, sum, na.rm = TRUE) %>% 
    mutate('Incidência Dengue' = 100000 * casos_dengue/Populacao,
           'Incidência Zika' = 100000 * casos_zika/Populacao,
           'Incidência Chikungunya' = 100000 * casos_chik/Populacao) %>% 
    rename('N° de casos Dengue' = casos_dengue, 'N° de casos Zika' = casos_zika, 
           'N° de casos Chikungunya' = casos_chik)
  
  print(kable(base_macro %>% 
                rename('Macrorregião' = macrorregiao, 'População' = Populacao), caption = paste0('Cenário de cocirculação de arboviroses nos municípios da Bahia, por macrorregião, em ', ano)))
  cat('\n')

  print(kable(base %>% 
                rename('Macrorregião' = macrorregiao, 'População' = Populacao,
                       'N° de casos Dengue' = casos_dengue, 
                        'N° de casos Zika' = casos_zika, 
           'N° de casos Chikungunya' = casos_chik), caption = paste0('Cenário de cocirculação de arboviroses nos municípios da Bahia em ', ano)))
  cat('\n')
}
```
