---
title: "Análise Descritiva Chikungunya"
output:
  html_document:
    highlight: tango
    lib_dir: libs
    number_sections: yes
    theme: yeti
    toc: yes
    toc_float:
      collapse: yes
  word_document:
    toc: yes
---

```{r setup,include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, comment = '', warning = FALSE)
```

```{r}
library(data.table)
library(tidyverse)
library(dplyr)
library(read.dbc)
library(foreign)
library(dplyr)
require("stringr")
require(summarytools)
library(rapportools)
source("http://pcwww.liv.ac.uk/~william/R/crosstab.r")
```

<!-- # Leitura da base -->
```{r}
library(tibble)
library(readxl)
```

```{r}
#nome.arquivo<-"Arboviroses casos confirmados notificados Bahia 2016 - 2019"
#load("G:/backup_maira/SINAN/analisebruno/arboviroses.Rdata")
#load("/cloud/project/fe_dataset_arboviroses_fase1.RData")
load("/cloud/project/fe_base de casos corrigidas/fe_dataset_arboviroses_fase1.RData")
load("/cloud/project/binomial/bases finais/base_analise_ha_v2.RData")
load("/cloud/project/binomial/bases finais/bahia_pop_long.RData")

```

```{r}
chik<-fe_chik_conf
```

# Estrutura da base

## chicungunya
```{r}
names(fe_chik_conf)
```
Casos confirmados por ano


```{r}
library(expss)
base_analise_ha_v2%>%dplyr::select(ano,chik_conf)%>%
 dplyr::filter(chik_conf>0)%>%
 group_by(ano)%>%  
 dplyr::summarise_at(c("chik_conf"), sum, na.rm = TRUE)%>%
 sort_asc(ano,chik_conf)%>%
 knitr::kable(.,"simple")

```
casos suspeitos por ano
```{r}
fe_chik_susp_muni%>%dplyr::select(NU_ANO,casos_chik)%>%
 dplyr::filter(casos_chik>0)%>%
 group_by(NU_ANO)%>%  
 count()%>%knitr::kable(.,"simple") 
```

# Localização dos casos autóctones

```{r}
#intersect(fe_chik_conf$MUN_RESI,fe_chik_conf$MUNI_RESI)
```

```{r}
  casos_municip_mes_ano = fe_chik_conf %>% 
    dplyr::select(MUNI_RESI,NU_ANO,TPAUTOCTO,DT_NOTIFIC,EVOLUCAO)%>%
    mutate(DT_NOTIFIC = as.Date(DT_NOTIFIC)) %>% 
    mutate(mes = format(DT_NOTIFIC, "%m")) %>% 
    group_by(NU_ANO, mes, MUNI_RESI)%>%count()%>%
    dplyr::rename(casos_chik=n)%>%dplyr::select(MUNI_RESI,everything())

casos_municip_mes_ano$MUNI_RESI<-gsub("DIAS D'AVILA", "DIAS D AVILA", casos_municip_mes_ano$MUNI_RESI)
casos_municip_mes_ano$MUNI_RESI<-replace(casos_municip_mes_ano$MUNI_RESI, casos_municip_mes_ano$MUNI_RESI=="Barrocas (BA)","BARROCAS")
casos_municip_mes_ano$MUNI_RESI<-replace(casos_municip_mes_ano$MUNI_RESI, casos_municip_mes_ano$MUNI_RESI=="Luis Eduardo Magalhaes (BA)","LUIS EDUARDO MAGALHAES")

```

```{r}
casos<-casos_municip_mes_ano[,2:4]

p<- casos %>% 
    dplyr::select(NU_ANO,mes)%>%
    group_by(mes,NU_ANO)%>%count()%>%
    dplyr::rename(casos_mes=n)%>%
    ggplot(aes(x=mes, y=casos_mes, fill=NU_ANO)) +
    geom_boxplot(alpha=0.2)+
    theme_ipsum() +
    xlab("Mês de notificação")+
    ylab("Casos confirmados")+
    theme(axis.text.y=element_text(size=6),axis.text.x = element_text(size=6))
p
```

```{r}
casos_municip_mes_ano %>% 
    dplyr::filter(TPAUTOCTO==1)%>%
    dplyr::select(NU_ANO,mes)%>%
    group_by(mes,NU_ANO)%>%count()%>%
    dplyr::rename(casos_mes=freq)%>%
    ggplot(aes(x=mes, y=casos_mes, fill=NU_ANO)) +
    geom_boxplot(alpha=0.2)+
    theme_ipsum() +
    xlab("Mês de notificação")+
    ylab("Casos confirmados")+
    theme(axis.text.y=element_text(size=6),axis.text.x = element_text(size=6)
        )

```

1-Cura
2- Óbito por chik
3- Óbito por outras causas
4 – Óbito em investigação
9- Ignorado
```{r}
casos_municip_mes_ano%>%dplyr::select(MUNI_RESI,NU_ANO,TPAUTOCTO,EVOLUCAO)%>%
   dplyr::filter(TPAUTOCTO==1)%>% dplyr::select(EVOLUCAO)%>%
   dfSummary(style='multiline', graph.col = FALSE)
   
```


```{r}
#DT_NOTIFIC,SEM_NOT

chik_bahia<-casos_municip_mes_ano%>%dplyr::select(MUNI_RESI,NU_ANO,TPAUTOCTO)%>%
   dplyr::filter(TPAUTOCTO==1)%>%
   group_by(MUNI_RESI,NU_ANO)%>%
   count()%>%
  dplyr::rename(casos_auto=freq)


chik_bahia$MUNI_RESI<-gsub("DIAS D'AVILA", "DIAS D AVILA", chik_bahia$MUNI_RESI)
chik_bahia$MUNI_RESI<-replace(chik_bahia$MUNI_RESI, chik_bahia$MUNI_RESI=="Barrocas (BA)","BARROCAS")
chik_bahia$MUNI_RESI<-replace(chik_bahia$MUNI_RESI, chik_bahia$MUNI_RESI=="Luis Eduardo Magalhaes (BA)","LUIS EDUARDO MAGALHAES")


chik_bahia<-chik_bahia%>%left_join(bahia_pop_long %>%
  dplyr::select(mun,ano,regiao.de.saude,macrorregiao,popporte,IDH_2015,IDH,bioma_2014),by = c('MUNI_RESI' = 'mun','NU_ANO'='ano'))%>%
  left_join(base_analise_ha_v2%>%dplyr::select(mun,ano,chik_conf,populacao,tipologia,semiarido),by = c('MUNI_RESI' = 'mun','NU_ANO'='ano'))%>%
  dplyr::rename(mun=MUNI_RESI,ano=NU_ANO, chik_auto=TPAUTOCTO)

```



```{r}
chik_bahia%>%dplyr::filter(ano==2016)%>%
dplyr::select(popporte,IDH,IDH_2015,bioma_2014)%>%
   dfSummary(style='multiline', graph.col = FALSE)
```

```{r}
base_analise_ha_v2 %>%dplyr::filter(chik_conf!=0)%>%
 dplyr::select(IDH,bioma_2014,ano)%>%
 dplyr::group_by(ano)%>%  
 dfSummary(style='multiline', graph.col = FALSE)
```


```{r}
chik_bahia%>% dplyr::filter(ano==2016)%>%dplyr::select(tipologia,semiarido)%>%
    dfSummary(style='multiline', graph.col = FALSE)
```

```{r}
chik_bahia%>%
dplyr::select(ano,macrorregiao,regiao.de.saude,chik_auto,chik_conf)%>%
 group_by(ano,macrorregiao,regiao.de.saude)%>%  
 dplyr::summarise_at(c("chik_auto", "chik_conf"), sum, na.rm = TRUE)%>%
 sort_asc(macrorregiao, regiao.de.saude, chik_auto,chik_conf)%>%
 dplyr::select(ano,macrorregiao,regiao.de.saude,chik_auto,chik_conf)%>%
  gather('variavel','casos',chik_conf,chik_auto) %>% 
  mutate(variavel = fct_reorder(variavel, casos,.desc = TRUE)) %>%
  ggplot( aes(x=casos, y=regiao.de.saude, fill=variavel)) +
    geom_bar(stat="identity", position="stack") +
    scale_fill_viridis(discrete=TRUE, name="") +
    theme_ipsum() +
    xlab(" Casos")+
    ylab("Região de saúde")+
    theme(axis.text.y=element_text(size=5),axis.text.x = element_text(size=5)
        )#+   facet_wrap(~ano)
```


```{r}
chik_bahia%>%
dplyr::select(ano,macrorregiao,regiao.de.saude,chik_auto,chik_conf)%>%
 group_by(ano,macrorregiao,regiao.de.saude)%>%  
 dplyr::summarise_at(c("chik_auto", "chik_conf"), sum, na.rm = TRUE)%>%
 sort_asc(macrorregiao, regiao.de.saude, chik_auto,chik_conf)%>%
 dplyr::select(ano,macrorregiao,regiao.de.saude,chik_auto,chik_conf)%>%
  gather('variavel','casos',chik_conf,chik_auto) %>% 
  mutate(variavel = fct_reorder(variavel, casos,.desc = TRUE)) %>%
  ggplot( aes(x=casos, y=macrorregiao, fill=variavel)) +
    geom_bar(stat="identity", position="stack") +
    scale_fill_viridis(discrete=TRUE, name="") +
    theme_ipsum() +
    xlab(" Casos")+
    ylab("Macrorregião")+
    theme(axis.text.y=element_text(size=5),axis.text.x = element_text(size=5)
        )#+   facet_wrap(~ano)


```

```{r}
chik_bahia%>%
dplyr::select(macrorregiao,chik_auto,chik_conf)%>%
 group_by(macrorregiao)%>%  
 dplyr::summarise_at(c("chik_auto", "chik_conf"), sum, na.rm = TRUE)%>%
 mutate(percent=round((chik_auto*100)/chik_conf),3)%>%
 sort_asc(percent,macrorregiao)%>%
 knitr::kable(.,"simple") 
 
```


```{r}
chik_bahia%>%
dplyr::select(macrorregiao,regiao.de.saude)%>%
 group_by(macrorregiao,regiao.de.saude)%>%
unique()%>%
 knitr::kable(.,"simple") 
```

```{r}
chik_bahia%>%
dplyr::select(regiao.de.saude,macrorregiao,chik_auto,chik_conf)%>%
 group_by(regiao.de.saude)%>%  
 dplyr::summarise_at(c("chik_auto", "chik_conf"), sum, na.rm = TRUE)%>%
 mutate(percent=round((chik_auto*100)/chik_conf),3)%>%
 sort_asc(chik_auto,regiao.de.saude)%>%
 knitr::kable(.,"simple") 
```

```{r}
png("/cloud/project/binomial/bases finais/auto_conf_macro.jpg") 

p<-chik_bahia%>%
dplyr::select(ano,macrorregiao,regiao.de.saude,chik_auto,chik_conf)%>%
 group_by(ano,macrorregiao,regiao.de.saude)%>%  
 dplyr::summarise_at(c("chik_auto", "chik_conf"), sum, na.rm = TRUE)%>%
 sort_asc(macrorregiao, regiao.de.saude, chik_auto,chik_conf)%>%
 dplyr::select(ano,macrorregiao,regiao.de.saude,chik_auto,chik_conf)%>%
  gather('variavel','casos',chik_conf,chik_auto) %>% 
  mutate(variavel = fct_reorder(variavel, casos,.desc = TRUE)) %>%
  ggplot(aes(x=casos, y=macrorregiao, fill=variavel)) +
    geom_boxplot(alpha=0.2)+
    theme_ipsum() +
    xlab(" Casos")+
    ylab("Macrorregião")+
    theme(axis.text.y=element_text(size=5),axis.text.x = element_text(size=5)
        )+facet_wrap(~variavel)+
  theme_bw() + 
  theme(axis.ticks.length = unit(-0.25, "cm"), 
        axis.ticks.margin = unit(0.5, "cm"))+
  theme(axis.title = element_text(size = 10),
        axis.text = element_text(size = 4)) +
  plot_layout(guides='collect') &
theme(legend.position='none')

print(p)
dev.off()

p
```

```{r}
png("/cloud/project/binomial/bases finais/auto_conf_rs.jpg") 

p<-chik_bahia%>%
dplyr::select(ano,macrorregiao,regiao.de.saude,chik_auto,chik_conf)%>%
 group_by(ano,macrorregiao,regiao.de.saude)%>%  
 dplyr::summarise_at(c("chik_auto", "chik_conf"), sum, na.rm = TRUE)%>%
 sort_asc(macrorregiao, regiao.de.saude, chik_auto,chik_conf)%>%
 dplyr::select(ano,macrorregiao,regiao.de.saude,chik_auto,chik_conf)%>%
  gather('variavel','casos',chik_conf,chik_auto) %>% 
  mutate(variavel = fct_reorder(variavel, casos,.desc = TRUE)) %>%
  ggplot(aes(x=casos, y=regiao.de.saude, fill=variavel)) +
    geom_boxplot(alpha=0.2)+
    theme_ipsum() +
    xlab(" Casos")+
    ylab("Região de Saúde")+
    theme(axis.text.y=element_text(size=5),axis.text.x = element_text(size=5)
        )+facet_wrap(~variavel)+
  theme_bw() + 
  theme(axis.ticks.length = unit(-0.25, "cm"), 
        axis.ticks.margin = unit(0.5, "cm"))+
  theme(axis.title = element_text(size = 10),
        axis.text = element_text(size = 4)) +
  plot_layout(guides='collect') &
theme(legend.position='none')

print(p)
dev.off()
p

```

## Frequencia de Casos Confirmados por ano


```{r}
bahia_chik<-incid_arboviroses_ano%>%left_join(bahia_pop_long %>%
  dplyr::select(mun,ano,area,popporte,regiao.de.saude,macrorregiao),by = c('mun' = 'mun','ano'='ano'))

```

```{r}
fe_chik_conf_muni%>%dplyr::select(Mun,casos_chik)%>%
 group_by(Mun)%>%  
 dplyr::summarise_at(c("casos_chik"), sum, na.rm = TRUE)%>%
 sort_asc(Mun,casos_chik)%>%
 knitr::kable(.,"simple")
```

# zika municipios ao longo dos 4 anos
 
```{r}
chik<-base_analise_ha_v2%>%dplyr::select(ano,mun,chik_conf)%>%
 dplyr::filter(chik_conf>0)%>%
 group_by(ano)

mun2016<-chik$mun[chik$ano==2016]
mun2017<-chik$mun[chik$ano==2017]
mun2018<-chik$mun[chik$ano==2018]
mun2019<-chik$mun[chik$ano==2019]
```

```{r}
uni_16_17<-intersect(mun2016,mun2017)
uni_161718<-intersect(uni_16_17,mun2018)
uni_16171819<-intersect(uni_161718,mun2019)
uni_16171819
```

## caracteristicas municipios
```{r}
load("/cloud/project/binomial/bases finais/indicadores_ba.RData")
indicadores_ba%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::filter(ano==2016)%>%
  dplyr::select(mun, pop_2015,cadu_Ssnis_2015,cadu_Ssnis)%>%
  group_by(mun)%>%
 # mutate(cadu_Ssnis=sum(cadu_Ssnis))%>%
  dplyr::summarise_at(c("cadu_Ssnis","pop_2015"), sum, na.rm = TRUE)%>%
  mutate(percent_Ssnis= round(((cadu_Ssnis/(pop_2015-1))*100),3))%>%# percentual
  sort_asc(percent_Ssnis,mun)%>%
  knitr::kable(.,"simple")
```


```{r}
percent_snis<-indicadores_ba%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::filter(ano==2016)%>%
  dplyr::select(mun, pop_2015,cadu_Ssnis_2015,cadu_Ssnis)%>%
  group_by(mun)%>%
 # mutate(cadu_Ssnis=sum(cadu_Ssnis))%>%
  dplyr::summarise_at(c("cadu_Ssnis","pop_2015"), sum, na.rm = TRUE)%>%
  mutate(percent_Ssnis= round(((cadu_Ssnis/(pop_2015-1))*100),3))%>%# percentual
  sort_asc(percent_Ssnis,mun)

percent_snis%>%
 # dfSummary(style='multiline', graph.col = FALSE)
  knitr::kable(.,"simple")
```

```{r}
bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::filter(ano==2016)%>%
  dplyr::select(mun,macrorregiao,regiao.de.saude,popporte,IDH,bioma_2014,newtipology,tipologia)%>%
  sort_desc(macrorregiao,regiao.de.saude)%>%
  knitr::kable(.,"simple")
  #knitr::kable(.,"pipe",align = "c")

```

```{r}
bahia_pop_long%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::filter(ano==2016)%>%
  dplyr::select(mun,macrorregiao,regiao.de.saude,popporte,IDH,bioma_2014,newtipology,tipologia,semiarido)%>%
  sort_desc(macrorregiao,regiao.de.saude)%>%
  dfSummary(style='multiline', graph.col = FALSE)
```

```{r}
base_analise_ha_v2%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::select(mun,ano,tx_vacina,tx_G12A,tx_fluxo,tx_cadunico_tot_pes_pob_ext)%>%
  gather('variavel','taxa',tx_vacina,tx_G12A,tx_fluxo,tx_cadunico_tot_pes_pob_ext)%>%
  mutate(variavel = fct_reorder(variavel, taxa,.desc = TRUE)) %>%
ggplot(aes(x=taxa, y=mun, fill=variavel)) +
    geom_boxplot(alpha=0.2)+
    theme_ipsum() +
    xlab(" Taxas do município")+
    ylab("Municipio")+
    theme(axis.text.y=element_text(size=5),axis.text.x = element_text(size=5)
        ) +facet_wrap(~variavel,nrow=2)
```

```{r}
base_analise_ha_v2%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::select(mun, chik_conf)%>%
  group_by(mun)%>%  
  dplyr::summarise_at(c("chik_conf"), sum, na.rm = TRUE)%>%
  sort_asc(mun,chik_conf)%>%
  left_join(bahia_pop_long %>%
              dplyr::filter(ano==2016)%>%
              dplyr::select(mun,macrorregiao,regiao.de.saude,popporte,IDH,bioma_2014,newtipology,tipologia,semiarido),by = c('mun' = 'mun'))%>%
  dplyr::select(mun,macrorregiao,regiao.de.saude,popporte,IDH,bioma_2014,tipologia,chik_conf)%>%
  sort_asc(macrorregiao,regiao.de.saude)%>%
  knitr::kable(.,"simple")
  
```

```{r}
base_analise_ha_v2%>%dplyr::filter(mun%in%uni_16171819)%>%
  dplyr::select(mun, chik_conf)%>%
  group_by(mun)%>%  
  dplyr::summarise_at(c("chik_conf"), sum, na.rm = TRUE)%>%
  sort_asc(mun,chik_conf)%>%
  left_join(bahia_pop_long %>%
              dplyr::filter(ano==2016)%>%

```

