---
title: "Cocirculação de casos"
output:
  word_document:
    toc: yes
  html_document:
    code_folding: hide
    highlight: tango
    lib_dir: libs
    number_sections: yes
    theme: yeti
    toc: yes
    toc_float:
      collapse: yes
  pdf_document:
    toc: yes
editor_options:
  markdown:
    wrap: 72
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, comment = '', warning = FALSE)
```

```{r}
library(data.table)
library(tidyverse)
library(read.dbc)
library(foreign)
library(dplyr)
require("stringr")
require(summarytools)
library(rapportools)
source("http://pcwww.liv.ac.uk/~william/R/crosstab.r")
```

<!-- # Leitura da base -->

```{r}
library(tibble)
library(readxl)
```

```{r}
nome.arquivo<-"Arboviroses casos confirmados notificados Bahia 2016 - 2019"
#load("G:/backup_maira/SINAN/analisebruno/arboviroses.Rdata")
#load("/cloud/project/fe_dataset_arboviroses_fase1.RData")
#load("/cloud/project/binomial/data_arbo_long_v6.RData")
#load("/cloud/project/binomial/data_cov.RData")
#load("/cloud/project/fe_datasets_municipio_att.RData")
#load("/cloud/project/binomial/data_arbo_autoc.RData")
#load("/cloud/project/binomial/data_arbo_long.RData")

load("/cloud/project/binomial/data_arbo_long_v8_att.RData") # versoa de 28/06 vgarcia
load("/cloud/project/binomial/data_arbo_long_v0107.RData") # versao atualizada como contagem de casos v.binomial
```



```{r}
#https://cran.r-project.org/web/packages/expss/vignettes/tables-with-labels.html
library(expss)
mt = apply_labels(data_arbo_long_v8,
                      mun = "Municipio da Bahia",
                      ano = "Ano",
                      dg_incidencia_conf = "Tx incidencia Dengue",
                      chik_incidencia_conf = "Tx incidencia Chikungunya",
                      zk_incidencia_conf = "Tx incidencia Zika",
                      PIB_percapita = "Pib percapita",
                      dg_taxa_susp = "Tx suspeito Dengue",
                      chik_taxa_susp = "Tx suspeito Chikungunya",
                      zk_taxa_susp = "Tx suspeito Zika",
                      newtipology="Tipo do Município", 
                      newtipology=c("intermediarioadjacente" = 1, "intermediarioremoto" = 2, 
                                    "ruraladjacente" = 3, "ruralremoto" = 4, "urbano" = 5),
                      dens_mean = "densidade media",
                      bioma_2014 = "Uso do Solo",
                      bioma_2014 = c("floresta"=1, "natural não florestal"=2,"Agropecuária"=3,
                                     "Area não vegetada"=4, "corpos d’água"=5),
                      fluxo_2016 = "Deslocamento em 2016",
                      grupo_SES_CRI_2014 = "Desenvolvimento Regiao de Saude",
                      grupo_SES_CRI_2014 = c("Baixo desenvolvimento e oferta de serviços"=1, "Médio/alto desenvolvimento e baixa oferta (e/ou média/alta) de serviços"=2, "Médio desenvolvimento e média/alta oferta de serviços"=3, "Alto desenvolvimentoe média/alta oferta de serviços"= 4, "Alto desenvolvimento e alta oferta de serviços"=5),
                      percent_ab ="tx cobertura atencao básica por habitante" ,
                      tx_G12A = "tx scobertura agua por habitante",
                      tx_G12B = "tx scobertura esgoto por habitante",
                      IDH_2010 = "indice desenvolvimento humando 2010",
                      semi.arido="Clima semi arido",
                      semi.arido= c("Semiarido"= 1,"Nao arido"=0),
                      regiao.de.saude = "Regiao de Saude do municipio",
                      macrorregiao = "Macro regiao do municipio",
                      popporte = "Porte do municipio por habitante",
                      idhm="indice desenvolvimento humando 2015",
                      renda_gini="renda gini de 2015",
                      desemprego="desemprego em 2015",
                      pobres="pop pobre em 2015",
                      extr_pobres= "extpop pobre em 2015",
                      cobertbf="cobertura bf em 2015",
                      vacina="cobertura vacina febre amarela",
                      cadu_Ssnis_2015="inscritos no cadu sem agua, esgoto e lixo em 2015",
                      pop="densidade populacional municipal",
                      dg_auto="taxa de casos de dengue autoctone por habitante",
                      chik_auto="taxa de casos de chikungunya autoctone por habitante",
                      zk_auto="taxa de casos de zika autoctone por habitante"
)
#cross_cases(distribuicao, regiao.de.saude, pop)
```

```{r}
distribuicao = mt%>% dplyr::select(ano,regiao.de.saude,macrorregiao,dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf, pop)%>% 
    na.omit()
```


```{r}
mt%>%replace(is.na(.), 0)%>%
  dplyr::select(ano,dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
 group_by(ano)%>%
  dplyr::summarise_at(c("dg_incidencia_conf", "chik_incidencia_conf","zk_incidencia_conf"), sum, na.rm = TRUE)%>%sort_desc(ano,dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>% rename(Ano=ano, "Incidência de Dengue"=dg_incidencia_conf,"Incidência de Chikungunya"=chik_incidencia_conf,"Incidência de Zika"=zk_incidencia_conf)%>%
  knitr::kable(.,"pipe",align = "c")
```


```{r}
#cross_cases(mt, regiao.de.saude, bioma_2014)
plot(dg_incidencia_conf~pop,data=distribuicao)+ abline(reg = lm(distribuicao$dg_incidencia_conf~distribuicao$pop),col = "red")
```
```{r}
plot(dg_incidencia_conf~dens_mean,data=mt)+ abline(reg = lm(mt$dg_incidencia_conf~mt$dens_mean),col = "red")
```

```{r}
plot(dg_incidencia_conf~dg_auto,data=mt)+ abline(reg = lm(mt$dg_incidencia_conf~mt$dg_auto),col = "red")
```

```{r}
plot(dg_incidencia_conf~chik_auto,data=mt)+ abline(reg = lm(mt$dg_incidencia_conf~mt$chik_auto),col = "red")
```


```{r}
plot(dg_incidencia_conf~zk_auto,data=mt)+ abline(reg = lm(mt$dg_incidencia_conf~mt$zk_auto),col = "red")
```

```{r}
plot(fluxo_2016~dg_auto,data=mt)+ abline(reg = lm(mt$fluxo_2016~mt$dg_auto),col = "red")
```


```{r}

plot(log(fluxo_2016)~dg_auto,data=mt)
```

```{r}
library(tidyverse) # for almost everything ;)
library(flextable) # for beautifying tables
library(dlookr)    # for the main event of the evening ;)

```


```{r}
data_teste<-data_arbo_long_v8%>%dplyr::select(3,6,16,17,15,24,30)
diagnose_numeric(data_teste) %>% flextable()
```


## Casos confirmados (anual) por Regiao de Saude

```{r}

#library(ggmosaic)
#ggplot(data = incid_arboviroses_ano) +geom_mosaic(aes(x = product(incidencia_conf), fill = ano)) 

#library(productplots)
#library(janitor)
#library(CGPfunctions)
#PlotXTabs(incid_arboviroses_ano, 2, 4, plottype = "stack")
#https://cran.r-project.org/web/packages/CGPfunctions/vignettes/Using-PlotXTabs.html
#https://cran.r-project.org/web/packages/CGPfunctions/vignettes/Using-PlotXTabs2.html

incid_arboviroses_ano<-distribuicao%>% 
  gather('variavel','incidencia_conf',dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>% 
  mutate(arbovirose=str_extract(variavel, "[a-z]+"))%>%
  dplyr::select(regiao.de.saude,ano,arbovirose,everything())%>%
  dplyr::select(-variavel)

x<-crosstab(incid_arboviroses_ano, row.vars = "regiao.de.saude", col.vars = "ano", type = "r")
x
```

```{r}
library(plotrix)
#pie3D(circ_2016,labels = labels(circ_2016),explode = 0.1, main =  "Co-circulacao arbovirus nas Regiões de Saúde 2016")
#library(vcd)
#assoc(circ_2016, shade=TRUE, legend=TRUE)
#mosaicplot(circ_2016, color = "skyblue2", main = "Title")

circ_2016<-x[["table"]] [,1]
circ_2016<-circ_2016[circ_2016!=0]
circ_2017<-x[["table"]] [,2]
circ_2017<-circ_2017[circ_2017!=0]
circ_2018<-x[["table"]] [,3]
circ_2018<-circ_2018[circ_2018!=0]
circ_2019<-x[["table"]] [,4]
circ_2019<-circ_2019[circ_2019!=0]

uni_16_17<-intersect(labels(circ_2016),labels(circ_2017))
uni_161718<-intersect(uni_16_17,labels(circ_2018))
uni_16171819<-intersect(uni_161718,labels(circ_2019))

circulacao_t<-circ_2016[labels(circ_2016)%in%uni_16171819]
circulacao_t_2<-circ_2017[labels(circ_2017)%in%uni_16171819]
circulacao_t_3<-circ_2018[labels(circ_2018)%in%uni_16171819]
circulacao_t_4<-circ_2019[labels(circ_2019)%in%uni_16171819]

circulacao_16171819<-circulacao_t+circulacao_t_2+circulacao_t_3+circulacao_t_4


diff_16<-setdiff(labels(circ_2016),labels(circ_2017))
diff_16<-setdiff(diff_16,labels(circ_2018))
diff_16<-setdiff(diff_16,labels(circ_2019))
circulacao_2016<-circ_2016[labels(circ_2016)%in%diff_16]

diff_17<-setdiff(labels(circ_2017),labels(circ_2016))
diff_17<-setdiff(diff_17,labels(circ_2018))
diff_17<-setdiff(diff_17,labels(circ_2019))
circulacao_2017<-circ_2016[labels(circ_2017)%in%diff_17]

diff_18<-setdiff(labels(circ_2018),labels(circ_2016))
diff_18<-setdiff(diff_18,labels(circ_2017))
diff_18<-setdiff(diff_18,labels(circ_2019))
circulacao_2018<-circ_2018[labels(circ_2018)%in%diff_18]

diff_19<-setdiff(labels(circ_2019),labels(circ_2016))
diff_19<-setdiff(diff_19,labels(circ_2017))
diff_19<-setdiff(diff_19,labels(circ_2018))
circulacao_2019<-circ_2019[labels(circ_2019)%in%diff_19]


```



```{r}
pie(circulacao_16171819,main = "Co-circulação arbovirus nas Regiões de Saúde, 2016-2019", col = rainbow(length(circulacao_16171819)))

```
```{r}
distribuicao%>%dplyr::filter(regiao.de.saude%in%uni_16171819)%>%
  dplyr::select(regiao.de.saude,dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
 group_by(regiao.de.saude)%>%
  dplyr::summarise_at(c("dg_incidencia_conf", "chik_incidencia_conf","zk_incidencia_conf"), sum, na.rm = TRUE)%>%sort_desc(dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
  knitr::kable(.,"simple")

```
```{r}
data_arbo_long_v8%>%dplyr::select(mun,ano,regiao.de.saude,macrorregiao,dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
  left_join(data_arbo_long_v8.1[ano==2019,],by = c('mun' = 'mun','ano'='ano'))%>%
  dplyr::filter(regiao.de.saude%in%uni_16171819)%>%
  dplyr::select(macrorregiao,regiao.de.saude,populacao)%>%
 group_by(macrorregiao)%>% 
  dplyr::summarise_at(c("populacao"), sum, na.rm = TRUE)%>%
  na.omit()%>%
  knitr::kable(.,"simple")
```


```{r}
distribuicao%>%dplyr::filter(regiao.de.saude%in%uni_16171819)%>%
  dplyr::select(regiao.de.saude,macrorregiao,dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
 group_by(regiao.de.saude, macrorregiao)%>%
  dplyr::summarise_at(c("dg_incidencia_conf", "chik_incidencia_conf","zk_incidencia_conf"), sum, na.rm = TRUE)%>%sort_desc(dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
  knitr::kable(.,"simple")
```

```{r}
distribuicao%>%dplyr::filter(regiao.de.saude%in%uni_16171819)%>%
  dplyr::select(macrorregiao,dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
 group_by(macrorregiao)%>%
  dplyr::summarise_at(c("dg_incidencia_conf", "chik_incidencia_conf","zk_incidencia_conf"), sum, na.rm = TRUE)%>%sort_desc(dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
  knitr::kable(.,"simple")
```

```{r}
crosstab(incid_arboviroses_ano, row.vars = "macrorregiao", col.vars = "ano", type = "r")
```


```{r}
distribuicao%>%dplyr::filter(regiao.de.saude%in%uni_16171819)%>%
  dplyr::select(regiao.de.saude,ano,dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
 group_by(regiao.de.saude, ano)%>%
  dplyr::summarise_at(c("dg_incidencia_conf", "chik_incidencia_conf","zk_incidencia_conf"), sum, na.rm = TRUE)%>%
  knitr::kable(.,"simple")
```

```{r}
pie(circulacao_2016,main = "Circulacao arbovirus nas Regiões de Saúde em 2016", col = rainbow(length(circulacao_2016)))
```

```{r}
#pie(circulacao_2017,main = "Circulacao arbovirus nas Regiões de Saúde em 2017", col = rainbow(length(circulacao_2017)))
```

```{r}
#pie(circulacao_2018,main = "Circulacao arbovirus nas Regiões de Saúde em 2018", col = rainbow(length(circulacao_2018)))
```

```{r}
pie(circulacao_2019,main = "Circulacao arbovirus nas Regiões de Saúde em 2019", col = rainbow(length(circulacao_2019)))
```

```{r}
data_cc<-mt%>%dplyr::filter(regiao.de.saude%in%uni_16171819)%>%
  dplyr::select(regiao.de.saude,ano,PIB_percapita,tx_G12A,tx_G12B,bioma_2014,semi.arido,vacina,pop,popporte,dg_auto,chik_auto,zk_auto)

#ftable(data_cc)
```

```{r}
library(ggmosaic)

RS_PIB = data_cc%>% dplyr::select(regiao.de.saude,PIB_percapita)%>% 
 group_by(regiao.de.saude)%>%
  dplyr::summarise_at(c("PIB_percapita"), sum, na.rm = TRUE)

#table(RS_PIB$regiao.de.saude,RS_PIB$PIB_percapita)%>%
mosaicplot(~ regiao.de.saude + PIB_percapita, data = RS_PIB, main = "Cocirculacao Mosaic Plot",
           sub = "PIB by RS",
           xlab = "PIB",
           ylab = "RS",
           las = 2,
           dir = c("h", "v"),
           cex.axis = 0.78,
           off = 40,
           border = "chocolate"
           )


```


```{r}
# apply(UCBAdmissions, 1:2, sum)
table(data_cc$regiao.de.saude,data_cc$bioma_2014)%>%mosaicplot(main = "Cocirculação Mosaic Plot",
           sub = "BIOMA by RS",
           xlab = "BIOMA",
           ylab = "RS",
           las = 2, #https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/par.html
           dir = c("h", "v"),
           #color = "skyblue2",
           color = 2:3,
           off = 40,
           cex.axis = 0.75,
           border = "chocolate")



```

```{r}
mosaicplot(~ regiao.de.saude+semi.arido, data = data_cc, main = "Cocirculacao Mosaic Plot",
           sub = "Clima by RS",
           xlab = "Clima",
           ylab = "RS",
           las = 2,
           dir = c("h", "v"),
           cex.axis = 0.78,
           off = 40,
           border = "chocolate"
           )
```
```{r}
#hist(~semi.arido, data = data_cc)
```

```{r}
data_cc%>% dplyr::select(regiao.de.saude,vacina)%>% 
 group_by(regiao.de.saude)%>%
  dplyr::summarise_at(c("vacina"), sum, na.rm = TRUE)%>%
  mosaicplot(~ regiao.de.saude+vacina, data=.,main = "Cocirculacao Mosaic Plot",
           sub = "Vacina by RS",
           xlab = "Vacina",
           ylab = "RS",
           las = 2,
           dir = c("h", "v"),
           cex.axis = 0.78,
           off = 40,
           border = "chocolate"
           )
```
```{r}
data_cc%>%
  ggplot(aes(x=vacina, color=ano, fill=regiao.de.saude)) +
  geom_density(alpha=0.3,size=1)
#+ scale_x_log10()
```

```{r}
#https://r-graph-gallery.com/135-stacked-density-graph.html
library(ggplot2)
library(dplyr)
library(hrbrthemes)

ggplot(data=data_cc, aes(x=vacina, group=ano, fill=ano)) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum()+
    facet_wrap(~ano) +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      axis.ticks.x=element_blank()
    )
```
```{r}
ggplot(data=data_cc, aes(x=vacina, group=ano, fill=ano)) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum()+
    facet_grid(ano ~ .)
```
```{r}
ggplot(data=data_cc, aes(x=vacina, group=ano, fill=ano, colour="red")) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum()+
    facet_wrap(~regiao.de.saude) +
    theme(
      legend.position="right",
      panel.spacing = unit(0.1, "lines"),
      axis.ticks.x=element_blank()
    )
```



```{r}
ggplot(data=data_cc, aes(x=vacina, group=regiao.de.saude, fill=regiao.de.saude)) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum()+
    facet_wrap(~ano) +
    theme(
      legend.position="bottom",
      panel.spacing = unit(0.1, "lines"),
      axis.ticks.x=element_blank()
    )
```
```{r}
data_cc%>%
  dplyr::select(regiao.de.saude,ano,vacina)%>%
 group_by(regiao.de.saude, ano)%>%
  dplyr::summarise_at(c("vacina"), sum, na.rm = TRUE)%>%sort_desc(ano,vacina)%>%
  knitr::kable(.,"simple")

```
```{r}
data_cc%>%
  dplyr::select(regiao.de.saude,ano,vacina)%>%
 group_by(regiao.de.saude)%>%
  dplyr::summarise_at(c("vacina"), sum, na.rm = TRUE)%>% sort_desc(vacina)%>%
  knitr::kable(.,"simple")
```


```{r}
data_cc%>% dplyr::select(regiao.de.saude,dg_auto)%>% 
 group_by(regiao.de.saude)%>%
  dplyr::summarise_at(c("dg_auto"), sum, na.rm = TRUE)%>%
  mosaicplot(~ regiao.de.saude+dg_auto, data=.,main = "Cocirculacao Mosaic Plot",
           sub = "Vacina by RS",
           xlab = "dg_auto",
           ylab = "RS",
           las = 2,
           dir = c("h", "v"),
           cex.axis = 0.78,
           off = 40,
           border = "chocolate"
           )
```
```{r}
mt%>%dplyr::filter(regiao.de.saude%in%uni_16171819)%>%
  dplyr::filter(dg_incidencia_conf!=0 & chik_incidencia_conf!=0 & zk_incidencia_conf!=0 )%>%
  dplyr::select(ano,regiao.de.saude,dg_auto,chik_auto,zk_auto)%>%
  group_by(regiao.de.saude)%>%
  dplyr::summarise_at(c("dg_auto", "chik_auto","zk_auto"), sum, na.rm = TRUE)%>%sort_desc(dg_auto,chik_auto,zk_auto)%>%
  knitr::kable(.,"simple")
```
```{r}
mt%>%dplyr::filter(regiao.de.saude%in%uni_16171819)%>%
  dplyr::filter(dg_incidencia_conf!=0 & chik_incidencia_conf!=0 & zk_incidencia_conf!=0 )%>%
  dplyr::select(ano,regiao.de.saude,dg_auto,chik_auto,zk_auto)%>%
  group_by(regiao.de.saude, ano)%>%
  dplyr::summarise_at(c("dg_auto", "chik_auto","zk_auto"), sum, na.rm = TRUE)%>%
  sort_asc(regiao.de.saude)%>%
  knitr::kable(.,"simple")

```
```{r}
auto_arboviroses_ano<-data_cc%>% dplyr::select(ano,regiao.de.saude,dg_auto,chik_auto,zk_auto)%>% 
  gather('variavel','tx_auto',dg_auto,chik_auto,zk_auto)%>% 
  mutate(arbovirose=str_extract(variavel, "[a-z]+"))%>%
  dplyr::select(regiao.de.saude,ano,arbovirose,everything())%>%
  dplyr::select(-variavel)

a<-crosstab(auto_arboviroses_ano, row.vars = "regiao.de.saude", col.vars = "ano", type = "r")
a
```



```{r}
mt%>%dplyr::filter(regiao.de.saude%in%uni_16171819)%>%
  dplyr::select(ano,mun,dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
  dplyr::filter(dg_incidencia_conf!=0 & chik_incidencia_conf!=0 & zk_incidencia_conf!=0 )%>%
  group_by(mun)%>%
  dplyr::summarise_at(c("dg_incidencia_conf", "chik_incidencia_conf","zk_incidencia_conf"), sum, na.rm = TRUE)%>%sort_desc(dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
  knitr::kable(.,"simple")
  

```

```{r}
mt%>%dplyr::filter(regiao.de.saude%in%uni_16171819)%>%
  dplyr::select(ano,mun,dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
  dplyr::filter(dg_incidencia_conf!=0 & chik_incidencia_conf!=0 & zk_incidencia_conf!=0 )%>%
  group_by(mun,ano)%>%
  dplyr::summarise_at(c("dg_incidencia_conf", "chik_incidencia_conf","zk_incidencia_conf"), sum, na.rm = TRUE)%>%
  knitr::kable(.,"simple")
```
Municipio cocirculacao

```{r}
aux<-mt%>%dplyr::filter(regiao.de.saude%in%uni_16171819)%>%
  dplyr::select(ano,mun,dg_incidencia_conf,chik_incidencia_conf,zk_incidencia_conf)%>%
  dplyr::filter(dg_incidencia_conf!=0 & chik_incidencia_conf!=0 & zk_incidencia_conf!=0 )%>%
  group_by(mun,ano)%>%
  dplyr::summarise_at(c("dg_incidencia_conf", "chik_incidencia_conf","zk_incidencia_conf"), sum, na.rm = TRUE)

pairs(~dg_incidencia_conf+chik_incidencia_conf+zk_incidencia_conf,data=aux,
   main="Simple Scatterplot Matrix")
```

```{r}
pairs(~dg_incidencia_conf+chik_incidencia_conf+zk_incidencia_conf+dg_auto+chik_auto+zk_auto,data=data_arbo_long_v8,main="Simple Scatterplot Matrix")
```

```{r}
data_arbo_long_v8_cocirc<-data_arbo_long_v8%>%dplyr::filter(regiao.de.saude%in%uni_16171819)%>%
  dplyr::filter(dg_incidencia_conf!=0 & chik_incidencia_conf!=0 & zk_incidencia_conf!=0 )

data_arbo_long_v8_circ_16<-data_arbo_long_v8%>%dplyr::filter(regiao.de.saude%in%diff_16)%>%
  dplyr::filter(dg_incidencia_conf!=0 & chik_incidencia_conf!=0 & zk_incidencia_conf!=0 )

data_arbo_long_v8_circ_19<-data_arbo_long_v8%>%dplyr::filter(regiao.de.saude%in%diff_19)%>%
  dplyr::filter(dg_incidencia_conf!=0 & chik_incidencia_conf!=0 & zk_incidencia_conf!=0 )

#save(data_arbo_long_v7_cocirc,data_arbo_long_v7_circ_16,data_arbo_long_v7_circ_19,file="/cloud/project/binomial/data_arbo_long_v7_cocirc.RData")

#save(data_arbo_long_v8_cocirc,data_arbo_long_v8_circ_16,data_arbo_long_v8_circ_19,file="/cloud/project/binomial/data_arbo_long_v8_cocirc.RData")
```


```{r}
plot(ano~PIB_percapita,data=data_arbo_long_v8_cocirc)+ abline(reg = lm(data_arbo_long_v8_cocirc$ano~data_arbo_long_v8_cocirc$PIB_percapita),col = "red")   
```

```{r}
boxplot(PIB_percapita~ano,data=data_arbo_long_v8_cocirc)
```

```{r}
plot(data_arbo_long_v8_cocirc$PIB_percapita,type = "l") # "l" for line
```

```{r}
#ggplot(data_arbo_long_v8_cocirc) + aes(x = grupo_SES_CRI_2014, y = PIB_percapita) +  geom_boxplot()
```

```{r}
library(dlookr)
library(labelled)

data_arbo_long_v8_cocirc %>% 
  target_by(popporte) %>%      
  relate(dg_incidencia_conf) %>% 
  plot()


```

```{r}
data_arbo_long_v8_cocirc %>% 
  target_by(macrorregiao) %>%      
  relate(dg_incidencia_conf) %>% 
  plot()
```
```{r}
data_arbo_long_v8_cocirc %>% 
  target_by(newtipology) %>%      
  relate(dg_incidencia_conf) %>% 
  plot()
```


```{r}
data_arbo_long_v8_cocirc %>% 
  target_by(bioma_2014) %>%      
  relate(dg_incidencia_conf) %>% 
  plot()
```
```{r}
pairs(~dg_incidencia_conf+chik_incidencia_conf+zk_incidencia_conf+dg_auto+chik_auto+zk_auto,data=data_arbo_long_v8_cocirc,main="Simple Scatterplot Matrix")
```




