---
title: "Matriz de correlação"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    highlight: tango
    lib_dir: libs
    number_sections: yes
    theme: yeti
    toc: yes
    toc_float:
      collapse: yes
  word_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, comment = '', warning = FALSE)
```


```{r cars}

#load the libraries so you have access to them in your workflow

library("lme4")
library("ggplot2")
library("HLMdiag")
#library("DHARMa")
library("car") #for the Levene test which we will not discuss here
library("Matrix")
library(dplyr);library(tidyr)
library(utils)
library(stringr)
library(data.table)
library(foreign)
require(abjutils)
library(gridExtra)
library(grid)
library(kableExtra)
```

```{r}
load("/cloud/project/binomial/bases finais/base_maira.RData")
data <- base_maira%>%rename(densidade=pop)
```

```{r}
#eliminasse os nulos
na_omit_data=data[complete.cases(data),]

```

## Mapa de calor exibindo a correlação de variaveis pelo método de spearman

```{r}
var_categorica<-c("mun","ano","populacao","IDH","semiarido","bioma","tipologia")
dt<-na_omit_data[,!colnames(na_omit_data)%in%var_categorica]
```


```{r}
library(corrplot)
M <- cor(dt[,!colnames(dt)%in% var_categorica],method = "spearman")
```


```{r}
library(psych)
arbo_corr.test<-corr.test(dt[,!colnames(dt)%in% var_categorica], method = "spearman", use = "complete.obs")$p

```


```{r}
corrplot(M, p.mat = arbo_corr.test, method = 'square', type = 'lower', insig='blank',number.cex = 0.8, order = 'FPC', diag=FALSE)
```



