---
title: "Descritiva Arboviroses Bahia (parte 4) - Atualizado (2022)" 
date: "`r Sys.Date()`"
output: 
  html_document:
    highlight: tango
    #number_sections: yes
    theme: yeti
    toc: yes
    toc_float:
      collapse: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, comment = '', warning = FALSE, fig.width = 20, fig.height = 12)
```

```{r include = FALSE}
library(dplyr)
library(tidyverse)
library(knitr)
library(zoo)
library(ggplot2)
#library(sf)
#load('fe_datasets_municipio_att.RData')
#load("fe_dataset_arboviroses_fase1.RData")
load("/cloud/project/fe_dataset_arboviroses_fase1.RData")
load("/cloud/project/fe_datasets_municipio_att.RData")
```

# Incidência de casos confirmados por tipo de município

```{r include=FALSE}
aux_pop = aux_pop %>% mutate(newtipology = case_when(
                               newtipology == 1 ~ 'Intermediario adjacente',
                               newtipology == 2 ~ 'Intermediario remoto', 
                               newtipology == 3 ~ 'Rural adjacente',
                               newtipology == 4 ~ 'Rural remoto',
                               newtipology == 5 ~ 'Urbano'))
```


```{r include=FALSE}
anos = 2016:2019
gera_tabela_tipo_munic = function(anos, base, arb){
  
  for(ano in anos){
    
    #base_arb = base %>% dplyr::filter(NU_ANO == ano) %>% 
    #  group_by(ID_MN_RESI, newtipology) %>% count() %>% rename('casos' = n) %>% 
    base_arb = base %>% dplyr::filter(NU_ANO == ano) %>% 
      inner_join(aux_pop %>% 
                   dplyr::select(IBGE_6, mun, newtipology, paste0('pop.', ano)), by = c('ID_MN_RESI' = 'IBGE_6')) %>% 
      rename(pop = paste0('pop.', ano))
    
    base_arb = base_arb %>% 
        group_by(newtipology) %>% 
        summarise('casos' = sum(casos), 'populacao' = sum(pop)) %>% 
        mutate('incidencia' = round(100000 * casos/populacao, 3)) %>% 
        rename('Nova tipologia' = newtipology, Casos = casos, 'População' = populacao, 'Incidência' = incidencia)
    
      print(kable(base_arb, caption = paste0('Incidência de casos confirmados da ', arb, ' por tipo de município, Bahia, ', ano)))
      cat('\n')
  }  
  
}

gera_graf_tipo_munic = function(anos, base, arb){
  for(ano in anos){
      graf_se = base %>% dplyr::filter(NU_ANO == ano) %>% 
        group_by(ID_MN_RESI, SEM_PRI_V) %>% count() %>% rename('casos' = n) %>% 
        inner_join(aux_pop %>% dplyr::select(IBGE_6, newtipology, paste0('pop.', ano)), 
                           by = c('ID_MN_RESI' = 'IBGE_6')) %>% rename('populacao' = paste0('pop.', ano))
      
      graf_se = graf_se %>% group_by(SEM_PRI_V, newtipology) %>% 
        summarise('casos' = sum(casos), 'populacao' = sum(populacao)) %>% 
        mutate('incidencia' = round(100000 * casos/populacao, 3))
      
      fig = ggplot(graf_se, aes(x = as.factor(SEM_PRI_V), y = incidencia, fill = as.factor(newtipology))) +
        geom_bar(stat = "identity", position = "stack") +
        labs(title = paste0('Incidência de casos confirmados da ', arb, ' por tipo de município em ', ano), y = 'Incidência', x = 'Semana Epidemiológica', fill = 'Tipo de Município') +
        scale_fill_brewer(palette = 'Accent') +
        #scale_fill_manual(breaks = c('1', '2', '3'), values = c('LightGreen', 'brown1', 'gray'), labels = c('Sim', 'Não', 'Indeterminado')) +
        theme_minimal() +
        theme(axis.text.x = element_text(size = 16), 
                axis.title.x = element_text(size = 18),
                axis.text.y = element_text(size = 16), 
                axis.title.y = element_text(size = 18),
                legend.text = element_text(size = 16),
                title = element_text(size = 18))
      print(fig)
      cat('\n\n')
      
      graf_mes = base %>% dplyr::filter(NU_ANO == ano) %>% 
        group_by(ID_MN_RESI, DT_NOTIFIC) %>% count() %>% rename('casos' = n) %>% 
        inner_join(aux_pop %>% dplyr::select(IBGE_6, newtipology, paste0('pop.', ano)), by = c('ID_MN_RESI' = 'IBGE_6')) %>% rename('populacao' = paste0('pop.', ano))
      
      graf_mes = graf_mes %>% 
        group_by(DT_NOTIFIC, newtipology) %>% 
        summarise('casos' = sum(casos), 'populacao' = sum(populacao)) %>% 
        mutate('DT_NOTIFIC' = months(as.Date(DT_NOTIFIC), abbreviate = TRUE)) %>% 
        group_by(DT_NOTIFIC, newtipology) %>% summarise('casos' = sum(casos), 
                                                        'populacao' = sum(populacao))
      
      graf_mes = graf_mes %>% 
        mutate('incidencia' = round(100000 * casos/populacao, 3),
                                     'DT_NOTIFIC' = factor(DT_NOTIFIC, levels = c('jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez')))
      
      fig = ggplot(graf_mes, aes(x = DT_NOTIFIC, y = incidencia, fill = as.factor(newtipology))) +
        geom_bar(stat = "identity", position = "stack") +
        labs(title = paste0('Incidência de casos confirmados da ', arb, ' por mês e tipo de município em ', ano), y = 'Incidência', x = 'Mês', fill = 'Tipo de Município') +
        scale_fill_brewer(palette = 'Accent') +
        theme_minimal() +
        theme(axis.text.x = element_text(size = 16), 
                axis.title.x = element_text(size = 18),
                axis.text.y = element_text(size = 16), 
                axis.title.y = element_text(size = 18),
                legend.text = element_text(size = 16),
                title = element_text(size = 18))
        print(fig)
        cat('\n\n')
#  }
  }  
}
```

## Dengue

### Tabela

```{r results='asis'}
#anos = sort(unique(unique(dng$NU_ANO), unique(zk$NU_ANO), unique(chik$NU_ANO)))
gera_tabela_tipo_munic(anos, fe_dengue_conf_muni %>% rename(casos = casos_dengue), 'Dengue')
```

### Gráfico

```{r results='asis'}
gera_graf_tipo_munic(anos, fe_dengue_conf, 'Dengue')
```

## Zika

### Tabela

```{r results='asis'}
#anos = sort(unique(unique(dng$NU_ANO), unique(zk$NU_ANO), unique(chik$NU_ANO)))
gera_tabela_tipo_munic(anos, fe_zika_conf_muni %>% rename(casos = casos_zika), 'Zika')
```

### Gráfico

```{r results='asis'}
gera_graf_tipo_munic(anos, fe_zika_conf, 'Zika')
```

## Chikungunya

### Tabela

```{r results='asis'}
#anos = sort(unique(unique(dng$NU_ANO), unique(zk$NU_ANO), unique(chik$NU_ANO)))
gera_tabela_tipo_munic(anos, fe_chik_conf_muni %>% rename(casos = casos_chik), 'Chikungunya')
```

### Gráfico

```{r results='asis'}
gera_graf_tipo_munic(anos, fe_chik_conf, 'Chikungunya')
```

# Incidência de casos confirmados por tipo autóctone

```{r include=FALSE}
gera_tabela_autocto = function(anos, base, arb){
  
  for(ano in anos){
    base_arb = base %>% dplyr::filter(!is.na(TPAUTOCTO) & NU_ANO == ano) %>% 
      group_by(ID_MN_RESI, TPAUTOCTO) %>% count() %>% rename('casos' = n) %>% 
      inner_join(aux_pop %>% dplyr::select(IBGE_6, mun, paste0('pop.', ano)), by = c('ID_MN_RESI' = 'IBGE_6')) %>% 
      rename(pop = paste0('pop.', ano))
    
    base_arb = base_arb %>%  
      mutate('incidencia' = round(100000 * casos/pop, 3),
              TPAUTOCTO = case_when(
                               TPAUTOCTO == 1 ~ "Sim",
                               TPAUTOCTO == 2 ~ "Não", 
                               TPAUTOCTO == 3 ~ "Indeterminado")) %>% 
      dplyr::select(!c(casos, pop)) %>% 
      pivot_wider(names_from = TPAUTOCTO, values_from = incidencia, values_fill = 0)
    
    base_arb = base_arb %>% 
      as.data.frame() %>% 
      dplyr::select(!c(ID_MN_RESI)) %>% 
      rename('Município' = mun)
      print(kable(base_arb, caption = paste0('Incidência de casos confirmados da ', arb, ' por município e tipo autóctone, Bahia, ', ano)))
      cat('\n')
  }  
  
}

gera_graf_autocto = function(anos, base, arb){
  for(ano in anos){
      graf_se = base %>% dplyr::filter(!is.na(TPAUTOCTO) & NU_ANO == ano) %>% 
        group_by(ID_MN_RESI, SEM_PRI_V, TPAUTOCTO) %>% count() %>% rename('casos' = n) %>%
        inner_join(aux_pop %>% dplyr::select(IBGE_6, mun, paste0('pop.', ano)), by = c('ID_MN_RESI' = 'IBGE_6')) %>% 
      rename(pop = paste0('pop.', ano))
      
      graf_se = graf_se %>% group_by(SEM_PRI_V, TPAUTOCTO) %>% 
        summarise('casos' = sum(casos), 'populacao' = sum(pop)) %>% 
        mutate('incidencia' = round(100000 * casos/populacao, 3))
      
      fig = ggplot(graf_se, aes(x = as.factor(SEM_PRI_V), y = incidencia, fill = as.factor(TPAUTOCTO))) +
        geom_bar(stat = "identity", position = "stack") +
        labs(title = paste0('Incidência de casos confirmados da ', arb, ' por tipo autóctone em ', ano), y = 'Incidência', x = 'Semana Epidemiológica', fill = 'Autóctone') +
        #scale_fill_brewer(palette = 'Set2') +
        scale_fill_manual(breaks = c('1', '2', '3'), values = c('LightGreen', 'brown1', 'gray'), labels = c('Sim', 'Não', 'Indeterminado')) +
        theme_minimal() +
        theme(axis.text.x = element_text(size = 16), 
                axis.title.x = element_text(size = 18),
                axis.text.y = element_text(size = 16), 
                axis.title.y = element_text(size = 18),
                legend.text = element_text(size = 16),
                title = element_text(size = 18))
      print(fig)
      cat('\n\n')
      
      graf_mes = base %>% dplyr::filter(!is.na(TPAUTOCTO) & NU_ANO == ano) %>% 
        group_by(ID_MN_RESI, DT_NOTIFIC, TPAUTOCTO) %>% count() %>% rename('casos' = n) %>% 
        inner_join(aux_pop %>% dplyr::select(IBGE_6, mun, paste0('pop.', ano)), by = c('ID_MN_RESI' = 'IBGE_6')) %>% 
      rename(pop = paste0('pop.', ano))
    
      graf_mes = graf_mes %>% 
        mutate('DT_NOTIFIC' = months(as.Date(DT_NOTIFIC), abbreviate = TRUE)) %>% 
        group_by(DT_NOTIFIC, TPAUTOCTO) %>% 
        summarise('casos' = sum(casos), 'populacao' = sum(pop)) %>% 
        mutate('incidencia' = round(100000 * casos/populacao, 3),
                                     'DT_NOTIFIC' = factor(DT_NOTIFIC, levels = c('jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez')))
      
      fig = ggplot(graf_mes, aes(x = DT_NOTIFIC, y = incidencia, fill = as.factor(TPAUTOCTO))) +
        geom_bar(stat = "identity", position = "stack") +
        labs(title = paste0('Incidência de casos confirmados da ', arb, ' por mês e tipo autóctone em ', ano), y = 'Incidência', x = 'Mês', fill = 'Autóctone') +
        #scale_fill_brewer(palette = 'Set3') +
        scale_fill_manual(breaks = c('1', '2', '3'), values = c('LightGreen', 'brown1', 'gray'), labels = c('Sim', 'Não', 'Indeterminado')) +
        theme_minimal() +
        theme(axis.text.x = element_text(size = 16), 
                axis.title.x = element_text(size = 18),
                axis.text.y = element_text(size = 16), 
                axis.title.y = element_text(size = 18),
                legend.text = element_text(size = 16),
                title = element_text(size = 18))
        print(fig)
        cat('\n\n')
#  }
  }  
}
```

## Dengue

### Tabela

```{r results='asis'}
#anos = sort(unique(unique(dng$NU_ANO), unique(zk$NU_ANO), unique(chik$NU_ANO)))
gera_tabela_autocto(anos, fe_dengue_conf, 'Dengue')
```

### Gráfico

```{r results='asis'}
gera_graf_autocto(anos, fe_dengue_conf, 'Dengue')
```

## Zika

### Tabela

```{r results='asis'}
#anos = sort(unique(unique(dng$NU_ANO), unique(zk$NU_ANO), unique(chik$NU_ANO)))
gera_tabela_autocto(anos, fe_zika_conf, 'Zika')
```

### Gráfico

```{r results='asis'}
gera_graf_autocto(anos, fe_zika_conf, 'Zika')
```

## Chikungunya

### Tabela

```{r results='asis'}
#anos = sort(unique(unique(dng$NU_ANO), unique(zk$NU_ANO), unique(chik$NU_ANO)))
gera_tabela_autocto(anos, fe_chik_conf, 'Chikungunya')
```

### Gráfico

```{r results='asis'}
gera_graf_autocto(anos, fe_chik_conf, 'Chikungunya')
```

