---
title: "Descritiva Arboviroses Bahia (parte 6) - Atualizado (2022)" 
date: "`r Sys.Date()`"
output: 
  html_document:
    highlight: tango
    #number_sections: yes
    theme: yeti
    toc: yes
    toc_float:
      collapse: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, comment = '', warning = FALSE, fig.width = 20, fig.height = 12)
```


```{r include = FALSE}
library(dplyr)
library(knitr)
load('fe_datasets_municipio_att.RData')
```

# Indicadores socioeconômicos dos municípios da Bahia

```{r results='asis'}

base_demog = aux_pop %>% select(mun, popporte, Tipologia_, distancia.capital, dens_mean, 
                                        grupo_SES_CRI_2014, IFDM_geral_2016, percent_medio_ab, SNIS_G12A_2015, SNIS_G12B_2015, IND22_CICLO_2016, IND22_CICLO_2017, IND22_CICLO_2018, IND22_CICLO_2019, mediaciclo22)
  
  colnames(base_demog) = c('Município', 'População', 'Tipologia', 'Dist. Capital', 'Densidade média', 
                           'Grupos socioeconômicos (2014)', 'IFDM (2016)', 'Cobertura_AB(%)', 'G12A', 'G12B', 
                           'IND22 2016', 'IND22 2017',
                           'IND22 2018', 'IND22 2019', 'Média IND22')
  
print(kable(base_demog, caption = 'Indicadores socioeconômicos dos municípios da Bahia.',
              align = c(rep('l', 5), 'c', rep('l', 9))))
```

# Indicadores demográficos dos municípios da Bahia

```{r results='asis'}
anos = 2016:2019
for(ano in anos){
  cols_ano = c(paste0('pop.', ano), paste0('densidade_', ano))

  if(ano != 2019){
      base_demog = aux_pop %>% 
        select(mun, area_km, cols_ano) %>% 
        rename('Município' = mun, 'Área(km)' = area_km, 'População' = paste0('pop.', ano), 
               'Densidade' = paste0('densidade_', ano))
  }else{
      base_demog = aux_pop %>% 
        select(mun, area_km, cols_ano, grupo_SES_CRI_2014) %>% 
        rename('Município' = mun, 'Área(km)' = area_km, 'População' = paste0('pop.', ano), 
               'Densidade' = paste0('densidade_', ano), 'Grupos socioeconômicos' = grupo_SES_CRI_2014)
  }
  
  print(kable(base_demog, caption = paste0('Indicadores demográficos dos municípios da Bahia em ', ano),
              align = c(rep('l', ncol(base_demog) - 1), 'c')))
  cat('\n')
}
```

