---
title: "Descritiva Arboviroses Bahia (parte 2) - Atualizado (2022)" 
date: "`r Sys.Date()`"
output: 
  html_document:
    highlight: tango
    #number_sections: yes
    theme: yeti
    toc: yes
    toc_float:
      collapse: yes
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, comment = '', warning = FALSE, fig.width = 20, fig.height = 12)
```

```{r include = FALSE}
library(dplyr)
library(tidyverse)
library(knitr)
library(zoo)
load('/cloud/project/fe_datasets_municipio_att.RData')
load("/cloud/project/fe_dataset_arboviroses_fase1.RData")
```

# Distribuição de casos confirmados por região de saude

## Por ano

```{r results='asis'}
for(ano in 2016:2019){
  
  base_dengue = fe_dengue_conf %>% rename('regiao_saude' = 'Região.de.Saúde') %>% 
    filter(NU_ANO == ano)
  
  distribuicao_dengue = base_dengue %>%  
    group_by(regiao_saude) %>% count() %>% rename('Dengue_N' = n) %>% 
    mutate('Dengue(%)' = round(100 * Dengue_N/sum(fe_dengue_conf_muni %>% 
                                                    filter(NU_ANO == ano) %>% as.data.frame() %>% select(casos_dengue)), 3))
  
  base_zika = fe_zika_conf %>% rename('regiao_saude' = 'Região.de.Saúde') %>% 
    filter(NU_ANO == ano)
  
  distribuicao_zika = base_zika %>%  
    group_by(regiao_saude) %>% count() %>% rename('Zika_N' = n) %>% 
    mutate('Zika(%)' = round(100 * Zika_N/sum(fe_zika_conf_muni %>% 
                                                filter(NU_ANO == ano) %>% as.data.frame() %>% select(casos_zika)), 3))
  
  distribuicao_casos = full_join(distribuicao_dengue, distribuicao_zika)
  
  base_chik = fe_chik_conf %>% rename('regiao_saude' = 'Região.de.Saúde') %>% 
    filter(NU_ANO == ano)
  
  distribuicao_chik = base_chik %>%  
    group_by(regiao_saude) %>% count() %>% rename('Chik_N' = n) %>% 
    mutate('Chik(%)' = round(100 * Chik_N/sum(fe_chik_conf_muni %>% 
                                                filter(NU_ANO == ano) %>% as.data.frame() %>% select(casos_chik)), 3))
  
  distribuicao_casos = full_join(distribuicao_casos, distribuicao_chik) %>% 
    mutate_if(is.numeric, coalesce, 0)
  
  # distribuicao = distribuicao %>% rename_at(c('N', 'rel'), list( ~paste0(names(bases_arb[i]), '_', .) ) )
  # 
  # #if(names(bases_arb[i]) == 'dng')
  # if(exits('distribuicao_casos'))
  #   distribuicao_casos = full_join(distribuicao_casos, distribuicao)
  # else
  #   distribuicao_casos = distribuicao
  
  #}
  
  #distribuicao_casos = distribuicao_casos %>% mutate_if(is.numeric, coalesce, 0)
  
  distribuicao_casos = cbind(distribuicao_casos, 'Total_N' = 
                               rowSums(distribuicao_casos[, c('Dengue_N', 'Zika_N', 'Chik_N')]))
  
  distribuicao_casos = cbind(distribuicao_casos, 'Total(%)' = round(100 * distribuicao_casos$Total_N/sum(distribuicao_casos$Total_N), 3))
  
  distribuicao_casos = rbind(distribuicao_casos, round(colSums(distribuicao_casos[, -1]), 2))
  
  distribuicao_casos = distribuicao_casos %>% mutate(regiao_saude = as.character(regiao_saude)) 
  
  distribuicao_casos$regiao_saude[nrow(distribuicao_casos)] = 'Bahia'
  
  # distribuicao_casos = distribuicao_casos %>% 
  #   rename('Região de Saúde' = regiao_saude, 'Dengue(%)' = dng_rel, 'Zika(%)' = zk_rel, 'Chik(%)' = chik_rel, 'Dengue_N' = dng_N, 'Zika_N' = zk_N, 'Chik_N' = chik_N)
  
  print(knitr::kable(distribuicao_casos %>% rename('Região de Saúde' = regiao_saude), caption = paste0('Distribuição dos casos confirmados das arboviroses (Dengue, Zika e Chikungunya) por região de saúde, Bahia, ', ano)))
  cat('\n')
}
```

## Por mês/ano

```{r results='asis'}
distribuicao_dengue = fe_dengue_conf %>% rename('regiao_saude' = 'Região.de.Saúde') %>% 
  mutate(mes_ano = format(as.Date(DT_NOTIFIC), "%m/%Y")) %>% 
  group_by(mes_ano, regiao_saude) %>% 
  count() %>% rename('Dengue_N' = n)

distribuicao_zika = fe_zika_conf %>% rename('regiao_saude' = 'Região.de.Saúde') %>% 
  mutate(mes_ano = format(as.Date(DT_NOTIFIC), "%m/%Y")) %>% 
  group_by(mes_ano, regiao_saude) %>% 
  count() %>% rename('Zika_N' = n)

distribuicao_casos = full_join(distribuicao_dengue, distribuicao_zika)

distribuicao_chik = fe_chik_conf %>% rename('regiao_saude' = 'Região.de.Saúde') %>% 
  mutate(mes_ano = format(as.Date(DT_NOTIFIC), "%m/%Y")) %>% 
  group_by(mes_ano, regiao_saude) %>% 
  count() %>% rename('Chik_N' = n)

distribuicao_casos = full_join(distribuicao_casos, distribuicao_chik) %>% 
  mutate_if(is.numeric, coalesce, 0)

#distribuicao_casos = inner_join(distribuicao_casos, casos_arboviroses_mes_ano)

distribuicao_casos = cbind(distribuicao_casos, 'Total_N' = rowSums(distribuicao_casos[, c('Dengue_N', 'Zika_N', 'Chik_N')], na.rm = TRUE))

meses = paste0(0, 1:9)
meses = c(meses, 10:12)

for(ano in 2016:2019){
  for(m in meses){
    
    distribuicao_mes = distribuicao_casos %>% filter(mes_ano == paste0(m, '/', ano)) 
    
    distribuicao_mes = distribuicao_mes %>% 
      mutate('Dengue(%)' = round(100 * Dengue_N/sum(distribuicao_mes$Dengue_N, na.rm = TRUE), 3),
             'Zika(%)' = round(100 * Zika_N/sum(distribuicao_mes$Zika_N, na.rm = TRUE), 3),
             'Chik(%)' = round(100 * Chik_N/sum(distribuicao_mes$Chik_N, na.rm = TRUE), 3),
             'Total(%)' = round(100 * Total_N/sum(distribuicao_mes$Total_N, na.rm = TRUE), 3)) %>% 
      as.data.frame() %>% 
      select(regiao_saude, Dengue_N, `Dengue(%)`, Zika_N, `Zika(%)`, Chik_N, `Chik(%)`, Total_N, `Total(%)`)
    
    
    distribuicao_mes = rbind(distribuicao_mes, round(colSums(distribuicao_mes[, -1]), 2))
    
    distribuicao_mes = distribuicao_mes %>% mutate(regiao_saude = as.character(regiao_saude)) %>% 
      mutate_if(is.numeric, coalesce, 0)
    
    distribuicao_mes$regiao_saude[nrow(distribuicao_mes)] = 'Bahia'
    
    # distribuicao_mes = distribuicao_mes %>%   
    #   rename('Região de Saúde' = regiao_saude, 'Dengue_N' = dng_N, 'Zika_N' = zk_N, 'Chik_N' = chik_N)
    # 
    print(knitr::kable(distribuicao_mes %>% rename('Região de Saúde' = regiao_saude), caption = paste0('Distribuição dos casos confirmados das arboviroses (Dengue, Zika e Chikungunya) por região de saúde, Bahia, ', m, '/', ano)))
    cat('\n')
  }
}
```
